// Code generated by protoc-gen-go. DO NOT EDIT.
// source: announcement.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCardResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardResponse) Reset()         { *m = CreateCardResponse{} }
func (m *CreateCardResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCardResponse) ProtoMessage()    {}
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{0}
}

func (m *CreateCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardResponse.Unmarshal(m, b)
}
func (m *CreateCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardResponse.Marshal(b, m, deterministic)
}
func (m *CreateCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardResponse.Merge(m, src)
}
func (m *CreateCardResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCardResponse.Size(m)
}
func (m *CreateCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardResponse proto.InternalMessageInfo

func (m *CreateCardResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateCardRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	PreferredLanguages   []string `protobuf:"bytes,3,rep,name=PreferredLanguages,proto3" json:"PreferredLanguages,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	DestinationCity      string   `protobuf:"bytes,6,opt,name=DestinationCity,proto3" json:"DestinationCity,omitempty"`
	DestinationCountry   string   `protobuf:"bytes,7,opt,name=DestinationCountry,proto3" json:"DestinationCountry,omitempty"`
	NumberOfTravelers    int32    `protobuf:"varint,8,opt,name=NumberOfTravelers,proto3" json:"NumberOfTravelers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardRequest) Reset()         { *m = CreateCardRequest{} }
func (m *CreateCardRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCardRequest) ProtoMessage()    {}
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{1}
}

func (m *CreateCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardRequest.Unmarshal(m, b)
}
func (m *CreateCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardRequest.Marshal(b, m, deterministic)
}
func (m *CreateCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardRequest.Merge(m, src)
}
func (m *CreateCardRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCardRequest.Size(m)
}
func (m *CreateCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardRequest proto.InternalMessageInfo

func (m *CreateCardRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateCardRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCardRequest) GetPreferredLanguages() []string {
	if m != nil {
		return m.PreferredLanguages
	}
	return nil
}

func (m *CreateCardRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CreateCardRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *CreateCardRequest) GetDestinationCity() string {
	if m != nil {
		return m.DestinationCity
	}
	return ""
}

func (m *CreateCardRequest) GetDestinationCountry() string {
	if m != nil {
		return m.DestinationCountry
	}
	return ""
}

func (m *CreateCardRequest) GetNumberOfTravelers() int32 {
	if m != nil {
		return m.NumberOfTravelers
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateCardResponse)(nil), "createCardResponse")
	proto.RegisterType((*CreateCardRequest)(nil), "createCardRequest")
}

func init() {
	proto.RegisterFile("announcement.proto", fileDescriptor_0080e911b962c5cf)
}

var fileDescriptor_0080e911b962c5cf = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x43, 0x91, 0x56, 0x46, 0x13, 0xd3, 0xf1, 0xb2, 0x31, 0x1e, 0x48, 0x4f, 0x1c, 0x0c,
	0x26, 0x1a, 0x1f, 0xa0, 0x42, 0x6f, 0xfe, 0x0b, 0xf6, 0xe4, 0x6d, 0x81, 0x29, 0x21, 0xda, 0x5d,
	0x9c, 0x5d, 0x4c, 0xfa, 0x84, 0xbe, 0x96, 0x81, 0x56, 0x25, 0xa5, 0xc7, 0xf9, 0x7d, 0xdf, 0xec,
	0xce, 0xcc, 0x07, 0x28, 0x95, 0xd2, 0x8d, 0xca, 0x69, 0x4d, 0xca, 0x46, 0x35, 0x6b, 0xab, 0x67,
	0x11, 0x60, 0xce, 0x24, 0x2d, 0xc5, 0x92, 0x8b, 0x94, 0x4c, 0xad, 0x95, 0x21, 0x14, 0x30, 0x79,
	0x24, 0x63, 0x64, 0x49, 0xc2, 0x09, 0x9c, 0xd0, 0x4f, 0x7f, 0xcb, 0xd9, 0xf7, 0x08, 0xa6, 0xfd,
	0x86, 0xcf, 0x86, 0x8c, 0xc5, 0x00, 0x4e, 0xe6, 0x79, 0x4e, 0xc6, 0x2c, 0xf5, 0x3b, 0xa9, 0x5d,
	0x4f, 0x1f, 0xb5, 0x8e, 0x84, 0x4c, 0xce, 0x55, 0x6d, 0x2b, 0xad, 0xc4, 0x68, 0xeb, 0xe8, 0x21,
	0x8c, 0x00, 0x5f, 0x98, 0x56, 0xc4, 0x4c, 0xc5, 0x83, 0x54, 0x65, 0x23, 0x4b, 0x32, 0xc2, 0x0d,
	0xdc, 0xd0, 0x4f, 0x0f, 0x28, 0x78, 0x09, 0xfe, 0xab, 0x95, 0x6c, 0x13, 0x69, 0x49, 0x1c, 0x75,
	0xef, 0xfd, 0x83, 0x76, 0x83, 0x85, 0x2a, 0x3a, 0xcd, 0xdb, 0x6e, 0xb0, 0x2b, 0x31, 0x84, 0xb3,
	0x84, 0x8c, 0xad, 0x94, 0x6c, 0xbf, 0x8d, 0x2b, 0xbb, 0x11, 0xe3, 0xce, 0xb1, 0x8f, 0xdb, 0x89,
	0xfa, 0x48, 0x37, 0xca, 0xf2, 0x46, 0x4c, 0x3a, 0xf3, 0x01, 0x05, 0xaf, 0x60, 0xfa, 0xd4, 0xac,
	0x33, 0xe2, 0xe7, 0xd5, 0x92, 0xe5, 0x17, 0x7d, 0x10, 0x1b, 0x71, 0x1c, 0x38, 0xa1, 0x97, 0x0e,
	0x85, 0x9b, 0x05, 0x9c, 0xce, 0x7b, 0x79, 0xe0, 0x1d, 0x40, 0xfc, 0x77, 0x58, 0xc4, 0x68, 0x70,
	0xe5, 0x8b, 0xf3, 0x68, 0x18, 0xd5, 0xbd, 0xf7, 0xe6, 0x5e, 0xd7, 0x59, 0x36, 0xee, 0xe2, 0xbc,
	0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x70, 0x8f, 0xbc, 0x5d, 0xe4, 0x01, 0x00, 0x00,
}
