version: '3.8'

services:
  gateway:
    build: ./gateway/
    container_name: gateway
    restart: on-failure
    depends_on:
      - authentication
    ports:
      - 9090:9090
    networks:
      - trekdestiny
    volumes:
      - type: bind
        source: ./gateway/
        target: /app
  authentication:
    build: ./services/authentication/
    container_name: authentication
    restart: on-failure
    depends_on:
      - db
    networks:
      - trekdestiny
    volumes:
      - type: bind
        source: ./services/authentication
        target: /app
  userprofile:
    build: ./services/userprofile/
    container_name: userprofile
    restart: on-failure
    depends_on:
      - db
    networks:
      - trekdestiny
    volumes:
      - type: bind
        source: ./services/userprofile
        target: /app
  announcement:
    build: ./services/announcement/
    container_name: announcement
    restart: on-failure
    depends_on:
      - db
      - rabbit
    networks:
      - trekdestiny
    volumes:
      - type: bind
        source: ./services/announcement
        target: /app
  notification:
    build: ./services/notification/
    container_name: notification
    restart: on-failure
    depends_on:
      - db
      - announcement
    networks:
      - trekdestiny
    volumes:
      - type: bind
        source: ./services/notification
        target: /app
    ports:
      - 9091:8083
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - rabbit-logs:/var/log/rabbitmq
    networks:
      - trekdestiny
    env_file:
      - rabbit.env
    restart: on-failure
  db:
    image: postgres:16.0-alpine
    container_name: db
    restart: on-failure
    networks:
      - trekdestiny
    volumes:
      - trekdestinyData:/var/lib/postgresql/data
    env_file:
      - postgres.env
  chat_db:
    image: postgres:16.0-alpine
    container_name: chat_db
    restart: on-failure
    networks:
      - trekdestiny
    volumes:
      - trekdestinyData_chat:/var/lib/postgresql/data
    env_file:
      - postgres.env
  chat:
    build: ./services/chat
    container_name: chat
    depends_on:
      - chat_db
    restart: on-failure
    networks:
      - trekdestiny
    ports:
      - 9092:8084
volumes:
  trekdestinyData:
  trekdestinyData_chat:
  rabbit-data:
  rabbit-logs:
networks:
  trekdestiny:
