#!/bin/bash
arg=$1
if [[ $arg == "proto" ]]; then
    read -p "protofile : " protofile
    read -p "service : " service
    read -p "is is gateway ? " is_gateway
    if [[ $is_gateway == "y" ]]; then
        if [ -d "./gateway/services/$service" ] 
        then
            rm -r gateway/services/$service
        fi
        protoc --proto_path=protos protos/$protofile --go_out=gateway/services --go-grpc_out=gateway/services
        mv gateway/services/pb gateway/services/$service
    else
        protoc --proto_path=protos protos/$protofile --go_out=services/$service --go-grpc_out=services/$service
    fi
elif [[ $arg == "test" ]]; then
  cd services/$2
  go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out
elif [[ $arg == "test-ci" ]]; then
    if [[ $2 == "gateway" ]]; then
        cd gateway
        go test ./...
    else 
        cd services/$2
        go test ./...
    fi
elif [[ $arg == "install-dependencies" ]]; then
    if [[ $2 == "gateway" ]]; then
        cd gateway
        go mod download
    else 
        cd services/$2
        go mod download 
    fi

elif [[ $arg == "test-all" ]]; then
        rm coverage.txt
        cd gateway
        go test ./... -cover >> ../coverage.txt
        cd ../services/announcement
        go test ./... -cover >> ../../coverage.txt
        cd ../userprofile
        go test ./... -cover >> ../../coverage.txt
        cd ../authentication
        go test ./... -cover >> ../../coverage.txt
        cd ../chat
        go test ./... -cover >> ../../coverage.txt 
        cd ../notification
        go test ./... -cover >> ../../coverage.txt 

        cd ../../

        echo "-------------------    ALL FILES   --------------------" 
        cat coverage.txt | grep %
        echo "------------------- FINAL COVERAGE --------------------"
        count=$(cat coverage.txt | grep % | wc -l)
        echo "TOTAL TESTS : $count"    
        mean=$(cat coverage.txt | grep % | awk '{print $5}' | tr -d % | awk '{ sum += $1; n++ } END { if (n > 0) print sum / n; }')
        echo "FINAL COVERAGE : $mean"

fi
