#!/bin/bash
arg=$1
if [[ $arg == "proto" ]]; then
    read -p "protofile : " protofile
    read -p "service : " service
    read -p "is is gateway ? " is_gateway
    if [[ $is_gateway == "y" ]]; then
        if [ -d "./gateway/services/$service" ] 
        then
            rm -r gateway/services/$service
        fi
        protoc --proto_path=protos protos/$protofile --go_out=gateway/services --go-grpc_out=gateway/services
        mv gateway/services/pb gateway/services/$service
    else
        protoc --proto_path=protos protos/$protofile --go_out=services/$service --go-grpc_out=services/$service
    fi
elif [[ $arg == "test" ]]; then
  cd services/$2
  go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out
elif [[ $arg == "test-ci" ]]; then
    if [[ $2 == "gateway" ]]; then
        cd gateway
        go test ./...
    else 
        cd services/$2
        go test ./...
    fi
elif [[ $arg == "install-dependencies" ]]; then
    if [[ $2 == "gateway" ]]; then
        cd gateway
        go mod download
    else 
        cd services/$2
        go mod download 
    fi
fi
