// Code generated by protoc-gen-go. DO NOT EDIT.
// source: announcement.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCardRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	PreferredLanguages   []string `protobuf:"bytes,3,rep,name=PreferredLanguages,proto3" json:"PreferredLanguages,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	DestinationCity      string   `protobuf:"bytes,6,opt,name=DestinationCity,proto3" json:"DestinationCity,omitempty"`
	DestinationState     string   `protobuf:"bytes,7,opt,name=DestinationState,proto3" json:"DestinationState,omitempty"`
	DestinationCountry   string   `protobuf:"bytes,8,opt,name=DestinationCountry,proto3" json:"DestinationCountry,omitempty"`
	NumberOfTravelers    int32    `protobuf:"varint,9,opt,name=NumberOfTravelers,proto3" json:"NumberOfTravelers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardRequest) Reset()         { *m = CreateCardRequest{} }
func (m *CreateCardRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCardRequest) ProtoMessage()    {}
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{0}
}

func (m *CreateCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardRequest.Unmarshal(m, b)
}
func (m *CreateCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardRequest.Marshal(b, m, deterministic)
}
func (m *CreateCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardRequest.Merge(m, src)
}
func (m *CreateCardRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCardRequest.Size(m)
}
func (m *CreateCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardRequest proto.InternalMessageInfo

func (m *CreateCardRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateCardRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCardRequest) GetPreferredLanguages() []string {
	if m != nil {
		return m.PreferredLanguages
	}
	return nil
}

func (m *CreateCardRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CreateCardRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *CreateCardRequest) GetDestinationCity() string {
	if m != nil {
		return m.DestinationCity
	}
	return ""
}

func (m *CreateCardRequest) GetDestinationState() string {
	if m != nil {
		return m.DestinationState
	}
	return ""
}

func (m *CreateCardRequest) GetDestinationCountry() string {
	if m != nil {
		return m.DestinationCountry
	}
	return ""
}

func (m *CreateCardRequest) GetNumberOfTravelers() int32 {
	if m != nil {
		return m.NumberOfTravelers
	}
	return 0
}

type CreateCardResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardResponse) Reset()         { *m = CreateCardResponse{} }
func (m *CreateCardResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCardResponse) ProtoMessage()    {}
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{1}
}

func (m *CreateCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardResponse.Unmarshal(m, b)
}
func (m *CreateCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardResponse.Marshal(b, m, deterministic)
}
func (m *CreateCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardResponse.Merge(m, src)
}
func (m *CreateCardResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCardResponse.Size(m)
}
func (m *CreateCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardResponse proto.InternalMessageInfo

func (m *CreateCardResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetCardRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	FilterValues         string   `protobuf:"bytes,2,opt,name=FilterValues,proto3" json:"FilterValues,omitempty"`
	SortValue            string   `protobuf:"bytes,3,opt,name=SortValue,proto3" json:"SortValue,omitempty"`
	PageSize             string   `protobuf:"bytes,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNumber           string   `protobuf:"bytes,5,opt,name=PageNumber,proto3" json:"PageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCardRequest) Reset()         { *m = GetCardRequest{} }
func (m *GetCardRequest) String() string { return proto.CompactTextString(m) }
func (*GetCardRequest) ProtoMessage()    {}
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{2}
}

func (m *GetCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardRequest.Unmarshal(m, b)
}
func (m *GetCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardRequest.Marshal(b, m, deterministic)
}
func (m *GetCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardRequest.Merge(m, src)
}
func (m *GetCardRequest) XXX_Size() int {
	return xxx_messageInfo_GetCardRequest.Size(m)
}
func (m *GetCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardRequest proto.InternalMessageInfo

func (m *GetCardRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetCardRequest) GetFilterValues() string {
	if m != nil {
		return m.FilterValues
	}
	return ""
}

func (m *GetCardRequest) GetSortValue() string {
	if m != nil {
		return m.SortValue
	}
	return ""
}

func (m *GetCardRequest) GetPageSize() string {
	if m != nil {
		return m.PageSize
	}
	return ""
}

func (m *GetCardRequest) GetPageNumber() string {
	if m != nil {
		return m.PageNumber
	}
	return ""
}

type CardRecord struct {
	CardId               int32    `protobuf:"varint,1,opt,name=CardId,proto3" json:"CardId,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	PreferredLanguages   []string `protobuf:"bytes,4,rep,name=PreferredLanguages,proto3" json:"PreferredLanguages,omitempty"`
	StartDate            string   `protobuf:"bytes,5,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,6,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	DestinationCity      string   `protobuf:"bytes,7,opt,name=DestinationCity,proto3" json:"DestinationCity,omitempty"`
	DestinationState     string   `protobuf:"bytes,8,opt,name=DestinationState,proto3" json:"DestinationState,omitempty"`
	DestinationCountry   string   `protobuf:"bytes,9,opt,name=DestinationCountry,proto3" json:"DestinationCountry,omitempty"`
	NumberOfTravelers    int32    `protobuf:"varint,10,opt,name=NumberOfTravelers,proto3" json:"NumberOfTravelers,omitempty"`
	Image                string   `protobuf:"bytes,11,opt,name=Image,proto3" json:"Image,omitempty"`
	UserUsername         string   `protobuf:"bytes,12,opt,name=UserUsername,proto3" json:"UserUsername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardRecord) Reset()         { *m = CardRecord{} }
func (m *CardRecord) String() string { return proto.CompactTextString(m) }
func (*CardRecord) ProtoMessage()    {}
func (*CardRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{3}
}

func (m *CardRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardRecord.Unmarshal(m, b)
}
func (m *CardRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardRecord.Marshal(b, m, deterministic)
}
func (m *CardRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardRecord.Merge(m, src)
}
func (m *CardRecord) XXX_Size() int {
	return xxx_messageInfo_CardRecord.Size(m)
}
func (m *CardRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CardRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CardRecord proto.InternalMessageInfo

func (m *CardRecord) GetCardId() int32 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *CardRecord) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CardRecord) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardRecord) GetPreferredLanguages() []string {
	if m != nil {
		return m.PreferredLanguages
	}
	return nil
}

func (m *CardRecord) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CardRecord) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *CardRecord) GetDestinationCity() string {
	if m != nil {
		return m.DestinationCity
	}
	return ""
}

func (m *CardRecord) GetDestinationState() string {
	if m != nil {
		return m.DestinationState
	}
	return ""
}

func (m *CardRecord) GetDestinationCountry() string {
	if m != nil {
		return m.DestinationCountry
	}
	return ""
}

func (m *CardRecord) GetNumberOfTravelers() int32 {
	if m != nil {
		return m.NumberOfTravelers
	}
	return 0
}

func (m *CardRecord) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CardRecord) GetUserUsername() string {
	if m != nil {
		return m.UserUsername
	}
	return ""
}

type GetCardResponse struct {
	Cards                []*CardRecord `protobuf:"bytes,1,rep,name=Cards,proto3" json:"Cards,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	PageCount            int32         `protobuf:"varint,3,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCardResponse) Reset()         { *m = GetCardResponse{} }
func (m *GetCardResponse) String() string { return proto.CompactTextString(m) }
func (*GetCardResponse) ProtoMessage()    {}
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{4}
}

func (m *GetCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardResponse.Unmarshal(m, b)
}
func (m *GetCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardResponse.Marshal(b, m, deterministic)
}
func (m *GetCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardResponse.Merge(m, src)
}
func (m *GetCardResponse) XXX_Size() int {
	return xxx_messageInfo_GetCardResponse.Size(m)
}
func (m *GetCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardResponse proto.InternalMessageInfo

func (m *GetCardResponse) GetCards() []*CardRecord {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *GetCardResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCardResponse) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type CreateOfferRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AnnouncementId       int32    `protobuf:"varint,2,opt,name=AnnouncementId,proto3" json:"AnnouncementId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOfferRequest) Reset()         { *m = CreateOfferRequest{} }
func (m *CreateOfferRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOfferRequest) ProtoMessage()    {}
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{5}
}

func (m *CreateOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOfferRequest.Unmarshal(m, b)
}
func (m *CreateOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOfferRequest.Marshal(b, m, deterministic)
}
func (m *CreateOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOfferRequest.Merge(m, src)
}
func (m *CreateOfferRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOfferRequest.Size(m)
}
func (m *CreateOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOfferRequest proto.InternalMessageInfo

func (m *CreateOfferRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateOfferRequest) GetAnnouncementId() int32 {
	if m != nil {
		return m.AnnouncementId
	}
	return 0
}

type CreateOfferResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOfferResponse) Reset()         { *m = CreateOfferResponse{} }
func (m *CreateOfferResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOfferResponse) ProtoMessage()    {}
func (*CreateOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{6}
}

func (m *CreateOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOfferResponse.Unmarshal(m, b)
}
func (m *CreateOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOfferResponse.Marshal(b, m, deterministic)
}
func (m *CreateOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOfferResponse.Merge(m, src)
}
func (m *CreateOfferResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOfferResponse.Size(m)
}
func (m *CreateOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOfferResponse proto.InternalMessageInfo

func (m *CreateOfferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetOfferRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AnnouncementId       int32    `protobuf:"varint,2,opt,name=AnnouncementId,proto3" json:"AnnouncementId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOfferRequest) Reset()         { *m = GetOfferRequest{} }
func (m *GetOfferRequest) String() string { return proto.CompactTextString(m) }
func (*GetOfferRequest) ProtoMessage()    {}
func (*GetOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{7}
}

func (m *GetOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOfferRequest.Unmarshal(m, b)
}
func (m *GetOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOfferRequest.Marshal(b, m, deterministic)
}
func (m *GetOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOfferRequest.Merge(m, src)
}
func (m *GetOfferRequest) XXX_Size() int {
	return xxx_messageInfo_GetOfferRequest.Size(m)
}
func (m *GetOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOfferRequest proto.InternalMessageInfo

func (m *GetOfferRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetOfferRequest) GetAnnouncementId() int32 {
	if m != nil {
		return m.AnnouncementId
	}
	return 0
}

type OfferRecord struct {
	HostId               int32    `protobuf:"varint,1,opt,name=HostId,proto3" json:"HostId,omitempty"`
	HostFirstName        string   `protobuf:"bytes,2,opt,name=HostFirstName,proto3" json:"HostFirstName,omitempty"`
	HostLastName         string   `protobuf:"bytes,3,opt,name=HostLastName,proto3" json:"HostLastName,omitempty"`
	HostUsername         string   `protobuf:"bytes,4,opt,name=HostUsername,proto3" json:"HostUsername,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=Image,proto3" json:"Image,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferRecord) Reset()         { *m = OfferRecord{} }
func (m *OfferRecord) String() string { return proto.CompactTextString(m) }
func (*OfferRecord) ProtoMessage()    {}
func (*OfferRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{8}
}

func (m *OfferRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferRecord.Unmarshal(m, b)
}
func (m *OfferRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferRecord.Marshal(b, m, deterministic)
}
func (m *OfferRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferRecord.Merge(m, src)
}
func (m *OfferRecord) XXX_Size() int {
	return xxx_messageInfo_OfferRecord.Size(m)
}
func (m *OfferRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferRecord.DiscardUnknown(m)
}

var xxx_messageInfo_OfferRecord proto.InternalMessageInfo

func (m *OfferRecord) GetHostId() int32 {
	if m != nil {
		return m.HostId
	}
	return 0
}

func (m *OfferRecord) GetHostFirstName() string {
	if m != nil {
		return m.HostFirstName
	}
	return ""
}

func (m *OfferRecord) GetHostLastName() string {
	if m != nil {
		return m.HostLastName
	}
	return ""
}

func (m *OfferRecord) GetHostUsername() string {
	if m != nil {
		return m.HostUsername
	}
	return ""
}

func (m *OfferRecord) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *OfferRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GetOfferResponse struct {
	Offers               []*OfferRecord `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetOfferResponse) Reset()         { *m = GetOfferResponse{} }
func (m *GetOfferResponse) String() string { return proto.CompactTextString(m) }
func (*GetOfferResponse) ProtoMessage()    {}
func (*GetOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{9}
}

func (m *GetOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOfferResponse.Unmarshal(m, b)
}
func (m *GetOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOfferResponse.Marshal(b, m, deterministic)
}
func (m *GetOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOfferResponse.Merge(m, src)
}
func (m *GetOfferResponse) XXX_Size() int {
	return xxx_messageInfo_GetOfferResponse.Size(m)
}
func (m *GetOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOfferResponse proto.InternalMessageInfo

func (m *GetOfferResponse) GetOffers() []*OfferRecord {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *GetOfferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetCardProfileRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCardProfileRequest) Reset()         { *m = GetCardProfileRequest{} }
func (m *GetCardProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetCardProfileRequest) ProtoMessage()    {}
func (*GetCardProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{10}
}

func (m *GetCardProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardProfileRequest.Unmarshal(m, b)
}
func (m *GetCardProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetCardProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardProfileRequest.Merge(m, src)
}
func (m *GetCardProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetCardProfileRequest.Size(m)
}
func (m *GetCardProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardProfileRequest proto.InternalMessageInfo

func (m *GetCardProfileRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type GetCardProfileResponse struct {
	Cards                []*CardRecord `protobuf:"bytes,1,rep,name=Cards,proto3" json:"Cards,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCardProfileResponse) Reset()         { *m = GetCardProfileResponse{} }
func (m *GetCardProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetCardProfileResponse) ProtoMessage()    {}
func (*GetCardProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{11}
}

func (m *GetCardProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardProfileResponse.Unmarshal(m, b)
}
func (m *GetCardProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetCardProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardProfileResponse.Merge(m, src)
}
func (m *GetCardProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetCardProfileResponse.Size(m)
}
func (m *GetCardProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardProfileResponse proto.InternalMessageInfo

func (m *GetCardProfileResponse) GetCards() []*CardRecord {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *GetCardProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreatePostRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AnnouncementId       int32    `protobuf:"varint,2,opt,name=AnnouncementId,proto3" json:"AnnouncementId,omitempty"`
	PostTitle            string   `protobuf:"bytes,3,opt,name=PostTitle,proto3" json:"PostTitle,omitempty"`
	HostRating           int32    `protobuf:"varint,4,opt,name=HostRating,proto3" json:"HostRating,omitempty"`
	PostBody             string   `protobuf:"bytes,5,opt,name=PostBody,proto3" json:"PostBody,omitempty"`
	ImageData            []byte   `protobuf:"bytes,6,opt,name=ImageData,proto3" json:"ImageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{12}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreatePostRequest) GetAnnouncementId() int32 {
	if m != nil {
		return m.AnnouncementId
	}
	return 0
}

func (m *CreatePostRequest) GetPostTitle() string {
	if m != nil {
		return m.PostTitle
	}
	return ""
}

func (m *CreatePostRequest) GetHostRating() int32 {
	if m != nil {
		return m.HostRating
	}
	return 0
}

func (m *CreatePostRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

func (m *CreatePostRequest) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

type CreatePostResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{13}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PostRecord struct {
	PostId               int32    `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	AnnouncementId       int32    `protobuf:"varint,2,opt,name=AnnouncementId,proto3" json:"AnnouncementId,omitempty"`
	HostId               int32    `protobuf:"varint,3,opt,name=HostId,proto3" json:"HostId,omitempty"`
	HostUsername         string   `protobuf:"bytes,4,opt,name=HostUsername,proto3" json:"HostUsername,omitempty"`
	HostImage            string   `protobuf:"bytes,5,opt,name=HostImage,proto3" json:"HostImage,omitempty"`
	GuestId              int32    `protobuf:"varint,6,opt,name=GuestId,proto3" json:"GuestId,omitempty"`
	GuestUsername        string   `protobuf:"bytes,7,opt,name=GuestUsername,proto3" json:"GuestUsername,omitempty"`
	GuestImage           string   `protobuf:"bytes,8,opt,name=GuestImage,proto3" json:"GuestImage,omitempty"`
	PostTitle            string   `protobuf:"bytes,9,opt,name=PostTitle,proto3" json:"PostTitle,omitempty"`
	HostRating           int32    `protobuf:"varint,10,opt,name=HostRating,proto3" json:"HostRating,omitempty"`
	PostBody             string   `protobuf:"bytes,11,opt,name=PostBody,proto3" json:"PostBody,omitempty"`
	PostImage            string   `protobuf:"bytes,12,opt,name=PostImage,proto3" json:"PostImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRecord) Reset()         { *m = PostRecord{} }
func (m *PostRecord) String() string { return proto.CompactTextString(m) }
func (*PostRecord) ProtoMessage()    {}
func (*PostRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{14}
}

func (m *PostRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRecord.Unmarshal(m, b)
}
func (m *PostRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRecord.Marshal(b, m, deterministic)
}
func (m *PostRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRecord.Merge(m, src)
}
func (m *PostRecord) XXX_Size() int {
	return xxx_messageInfo_PostRecord.Size(m)
}
func (m *PostRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PostRecord proto.InternalMessageInfo

func (m *PostRecord) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PostRecord) GetAnnouncementId() int32 {
	if m != nil {
		return m.AnnouncementId
	}
	return 0
}

func (m *PostRecord) GetHostId() int32 {
	if m != nil {
		return m.HostId
	}
	return 0
}

func (m *PostRecord) GetHostUsername() string {
	if m != nil {
		return m.HostUsername
	}
	return ""
}

func (m *PostRecord) GetHostImage() string {
	if m != nil {
		return m.HostImage
	}
	return ""
}

func (m *PostRecord) GetGuestId() int32 {
	if m != nil {
		return m.GuestId
	}
	return 0
}

func (m *PostRecord) GetGuestUsername() string {
	if m != nil {
		return m.GuestUsername
	}
	return ""
}

func (m *PostRecord) GetGuestImage() string {
	if m != nil {
		return m.GuestImage
	}
	return ""
}

func (m *PostRecord) GetPostTitle() string {
	if m != nil {
		return m.PostTitle
	}
	return ""
}

func (m *PostRecord) GetHostRating() int32 {
	if m != nil {
		return m.HostRating
	}
	return 0
}

func (m *PostRecord) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

func (m *PostRecord) GetPostImage() string {
	if m != nil {
		return m.PostImage
	}
	return ""
}

type GetMyPostRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyPostRequest) Reset()         { *m = GetMyPostRequest{} }
func (m *GetMyPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetMyPostRequest) ProtoMessage()    {}
func (*GetMyPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{15}
}

func (m *GetMyPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyPostRequest.Unmarshal(m, b)
}
func (m *GetMyPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyPostRequest.Marshal(b, m, deterministic)
}
func (m *GetMyPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyPostRequest.Merge(m, src)
}
func (m *GetMyPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetMyPostRequest.Size(m)
}
func (m *GetMyPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyPostRequest proto.InternalMessageInfo

func (m *GetMyPostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type GetMyPostResponse struct {
	Posts                []*PostRecord `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMyPostResponse) Reset()         { *m = GetMyPostResponse{} }
func (m *GetMyPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetMyPostResponse) ProtoMessage()    {}
func (*GetMyPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{16}
}

func (m *GetMyPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyPostResponse.Unmarshal(m, b)
}
func (m *GetMyPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyPostResponse.Marshal(b, m, deterministic)
}
func (m *GetMyPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyPostResponse.Merge(m, src)
}
func (m *GetMyPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetMyPostResponse.Size(m)
}
func (m *GetMyPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyPostResponse proto.InternalMessageInfo

func (m *GetMyPostResponse) GetPosts() []*PostRecord {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *GetMyPostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetPostHostRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	HostId               int32    `protobuf:"varint,2,opt,name=HostId,proto3" json:"HostId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostHostRequest) Reset()         { *m = GetPostHostRequest{} }
func (m *GetPostHostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostHostRequest) ProtoMessage()    {}
func (*GetPostHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{17}
}

func (m *GetPostHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostHostRequest.Unmarshal(m, b)
}
func (m *GetPostHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostHostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostHostRequest.Merge(m, src)
}
func (m *GetPostHostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostHostRequest.Size(m)
}
func (m *GetPostHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostHostRequest proto.InternalMessageInfo

func (m *GetPostHostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetPostHostRequest) GetHostId() int32 {
	if m != nil {
		return m.HostId
	}
	return 0
}

type GetPostHostResponse struct {
	Posts                []*PostRecord `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPostHostResponse) Reset()         { *m = GetPostHostResponse{} }
func (m *GetPostHostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostHostResponse) ProtoMessage()    {}
func (*GetPostHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{18}
}

func (m *GetPostHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostHostResponse.Unmarshal(m, b)
}
func (m *GetPostHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostHostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostHostResponse.Merge(m, src)
}
func (m *GetPostHostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostHostResponse.Size(m)
}
func (m *GetPostHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostHostResponse proto.InternalMessageInfo

func (m *GetPostHostResponse) GetPosts() []*PostRecord {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *GetPostHostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AcceptOfferRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AnnouncementId       int32    `protobuf:"varint,2,opt,name=AnnouncementId,proto3" json:"AnnouncementId,omitempty"`
	HostId               int32    `protobuf:"varint,3,opt,name=HostId,proto3" json:"HostId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptOfferRequest) Reset()         { *m = AcceptOfferRequest{} }
func (m *AcceptOfferRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptOfferRequest) ProtoMessage()    {}
func (*AcceptOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{19}
}

func (m *AcceptOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptOfferRequest.Unmarshal(m, b)
}
func (m *AcceptOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptOfferRequest.Marshal(b, m, deterministic)
}
func (m *AcceptOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptOfferRequest.Merge(m, src)
}
func (m *AcceptOfferRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptOfferRequest.Size(m)
}
func (m *AcceptOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptOfferRequest proto.InternalMessageInfo

func (m *AcceptOfferRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AcceptOfferRequest) GetAnnouncementId() int32 {
	if m != nil {
		return m.AnnouncementId
	}
	return 0
}

func (m *AcceptOfferRequest) GetHostId() int32 {
	if m != nil {
		return m.HostId
	}
	return 0
}

type AcceptOfferResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptOfferResponse) Reset()         { *m = AcceptOfferResponse{} }
func (m *AcceptOfferResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptOfferResponse) ProtoMessage()    {}
func (*AcceptOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{20}
}

func (m *AcceptOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptOfferResponse.Unmarshal(m, b)
}
func (m *AcceptOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptOfferResponse.Marshal(b, m, deterministic)
}
func (m *AcceptOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptOfferResponse.Merge(m, src)
}
func (m *AcceptOfferResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptOfferResponse.Size(m)
}
func (m *AcceptOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptOfferResponse proto.InternalMessageInfo

func (m *AcceptOfferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RejectOfferRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AnnouncementId       int32    `protobuf:"varint,2,opt,name=AnnouncementId,proto3" json:"AnnouncementId,omitempty"`
	HostId               int32    `protobuf:"varint,3,opt,name=HostId,proto3" json:"HostId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectOfferRequest) Reset()         { *m = RejectOfferRequest{} }
func (m *RejectOfferRequest) String() string { return proto.CompactTextString(m) }
func (*RejectOfferRequest) ProtoMessage()    {}
func (*RejectOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{21}
}

func (m *RejectOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectOfferRequest.Unmarshal(m, b)
}
func (m *RejectOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectOfferRequest.Marshal(b, m, deterministic)
}
func (m *RejectOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectOfferRequest.Merge(m, src)
}
func (m *RejectOfferRequest) XXX_Size() int {
	return xxx_messageInfo_RejectOfferRequest.Size(m)
}
func (m *RejectOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejectOfferRequest proto.InternalMessageInfo

func (m *RejectOfferRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RejectOfferRequest) GetAnnouncementId() int32 {
	if m != nil {
		return m.AnnouncementId
	}
	return 0
}

func (m *RejectOfferRequest) GetHostId() int32 {
	if m != nil {
		return m.HostId
	}
	return 0
}

type RejectOfferResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectOfferResponse) Reset()         { *m = RejectOfferResponse{} }
func (m *RejectOfferResponse) String() string { return proto.CompactTextString(m) }
func (*RejectOfferResponse) ProtoMessage()    {}
func (*RejectOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{22}
}

func (m *RejectOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectOfferResponse.Unmarshal(m, b)
}
func (m *RejectOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectOfferResponse.Marshal(b, m, deterministic)
}
func (m *RejectOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectOfferResponse.Merge(m, src)
}
func (m *RejectOfferResponse) XXX_Size() int {
	return xxx_messageInfo_RejectOfferResponse.Size(m)
}
func (m *RejectOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejectOfferResponse proto.InternalMessageInfo

func (m *RejectOfferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EditAnnouncementRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	CardId               int32    `protobuf:"varint,2,opt,name=CardId,proto3" json:"CardId,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	PreferredLanguages   []string `protobuf:"bytes,4,rep,name=PreferredLanguages,proto3" json:"PreferredLanguages,omitempty"`
	StartDate            string   `protobuf:"bytes,5,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,6,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	DestinationCity      string   `protobuf:"bytes,7,opt,name=DestinationCity,proto3" json:"DestinationCity,omitempty"`
	DestinationState     string   `protobuf:"bytes,8,opt,name=DestinationState,proto3" json:"DestinationState,omitempty"`
	DestinationCountry   string   `protobuf:"bytes,9,opt,name=DestinationCountry,proto3" json:"DestinationCountry,omitempty"`
	NumberOfTravelers    int32    `protobuf:"varint,10,opt,name=NumberOfTravelers,proto3" json:"NumberOfTravelers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditAnnouncementRequest) Reset()         { *m = EditAnnouncementRequest{} }
func (m *EditAnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*EditAnnouncementRequest) ProtoMessage()    {}
func (*EditAnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{23}
}

func (m *EditAnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditAnnouncementRequest.Unmarshal(m, b)
}
func (m *EditAnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditAnnouncementRequest.Marshal(b, m, deterministic)
}
func (m *EditAnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditAnnouncementRequest.Merge(m, src)
}
func (m *EditAnnouncementRequest) XXX_Size() int {
	return xxx_messageInfo_EditAnnouncementRequest.Size(m)
}
func (m *EditAnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditAnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditAnnouncementRequest proto.InternalMessageInfo

func (m *EditAnnouncementRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *EditAnnouncementRequest) GetCardId() int32 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *EditAnnouncementRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditAnnouncementRequest) GetPreferredLanguages() []string {
	if m != nil {
		return m.PreferredLanguages
	}
	return nil
}

func (m *EditAnnouncementRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *EditAnnouncementRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *EditAnnouncementRequest) GetDestinationCity() string {
	if m != nil {
		return m.DestinationCity
	}
	return ""
}

func (m *EditAnnouncementRequest) GetDestinationState() string {
	if m != nil {
		return m.DestinationState
	}
	return ""
}

func (m *EditAnnouncementRequest) GetDestinationCountry() string {
	if m != nil {
		return m.DestinationCountry
	}
	return ""
}

func (m *EditAnnouncementRequest) GetNumberOfTravelers() int32 {
	if m != nil {
		return m.NumberOfTravelers
	}
	return 0
}

type EditAnnouncementResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditAnnouncementResponse) Reset()         { *m = EditAnnouncementResponse{} }
func (m *EditAnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*EditAnnouncementResponse) ProtoMessage()    {}
func (*EditAnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{24}
}

func (m *EditAnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditAnnouncementResponse.Unmarshal(m, b)
}
func (m *EditAnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditAnnouncementResponse.Marshal(b, m, deterministic)
}
func (m *EditAnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditAnnouncementResponse.Merge(m, src)
}
func (m *EditAnnouncementResponse) XXX_Size() int {
	return xxx_messageInfo_EditAnnouncementResponse.Size(m)
}
func (m *EditAnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditAnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditAnnouncementResponse proto.InternalMessageInfo

func (m *EditAnnouncementResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteAnnouncementRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	CardId               int32    `protobuf:"varint,2,opt,name=CardId,proto3" json:"CardId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnnouncementRequest) Reset()         { *m = DeleteAnnouncementRequest{} }
func (m *DeleteAnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAnnouncementRequest) ProtoMessage()    {}
func (*DeleteAnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{25}
}

func (m *DeleteAnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnnouncementRequest.Unmarshal(m, b)
}
func (m *DeleteAnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnnouncementRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnnouncementRequest.Merge(m, src)
}
func (m *DeleteAnnouncementRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAnnouncementRequest.Size(m)
}
func (m *DeleteAnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnnouncementRequest proto.InternalMessageInfo

func (m *DeleteAnnouncementRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *DeleteAnnouncementRequest) GetCardId() int32 {
	if m != nil {
		return m.CardId
	}
	return 0
}

type DeleteAnnouncementResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnnouncementResponse) Reset()         { *m = DeleteAnnouncementResponse{} }
func (m *DeleteAnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAnnouncementResponse) ProtoMessage()    {}
func (*DeleteAnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{26}
}

func (m *DeleteAnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnnouncementResponse.Unmarshal(m, b)
}
func (m *DeleteAnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnnouncementResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnnouncementResponse.Merge(m, src)
}
func (m *DeleteAnnouncementResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAnnouncementResponse.Size(m)
}
func (m *DeleteAnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnnouncementResponse proto.InternalMessageInfo

func (m *DeleteAnnouncementResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EditPostRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	PostId               int32    `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	PostTitle            string   `protobuf:"bytes,3,opt,name=PostTitle,proto3" json:"PostTitle,omitempty"`
	HostRating           int32    `protobuf:"varint,4,opt,name=HostRating,proto3" json:"HostRating,omitempty"`
	PostBody             string   `protobuf:"bytes,5,opt,name=PostBody,proto3" json:"PostBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditPostRequest) Reset()         { *m = EditPostRequest{} }
func (m *EditPostRequest) String() string { return proto.CompactTextString(m) }
func (*EditPostRequest) ProtoMessage()    {}
func (*EditPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{27}
}

func (m *EditPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditPostRequest.Unmarshal(m, b)
}
func (m *EditPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditPostRequest.Marshal(b, m, deterministic)
}
func (m *EditPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditPostRequest.Merge(m, src)
}
func (m *EditPostRequest) XXX_Size() int {
	return xxx_messageInfo_EditPostRequest.Size(m)
}
func (m *EditPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditPostRequest proto.InternalMessageInfo

func (m *EditPostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *EditPostRequest) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *EditPostRequest) GetPostTitle() string {
	if m != nil {
		return m.PostTitle
	}
	return ""
}

func (m *EditPostRequest) GetHostRating() int32 {
	if m != nil {
		return m.HostRating
	}
	return 0
}

func (m *EditPostRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type EditPostResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditPostResponse) Reset()         { *m = EditPostResponse{} }
func (m *EditPostResponse) String() string { return proto.CompactTextString(m) }
func (*EditPostResponse) ProtoMessage()    {}
func (*EditPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{28}
}

func (m *EditPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditPostResponse.Unmarshal(m, b)
}
func (m *EditPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditPostResponse.Marshal(b, m, deterministic)
}
func (m *EditPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditPostResponse.Merge(m, src)
}
func (m *EditPostResponse) XXX_Size() int {
	return xxx_messageInfo_EditPostResponse.Size(m)
}
func (m *EditPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditPostResponse proto.InternalMessageInfo

func (m *EditPostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HostHouseImageRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	ImageData            [][]byte `protobuf:"bytes,2,rep,name=ImageData,proto3" json:"ImageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostHouseImageRequest) Reset()         { *m = HostHouseImageRequest{} }
func (m *HostHouseImageRequest) String() string { return proto.CompactTextString(m) }
func (*HostHouseImageRequest) ProtoMessage()    {}
func (*HostHouseImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{29}
}

func (m *HostHouseImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostHouseImageRequest.Unmarshal(m, b)
}
func (m *HostHouseImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostHouseImageRequest.Marshal(b, m, deterministic)
}
func (m *HostHouseImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostHouseImageRequest.Merge(m, src)
}
func (m *HostHouseImageRequest) XXX_Size() int {
	return xxx_messageInfo_HostHouseImageRequest.Size(m)
}
func (m *HostHouseImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostHouseImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostHouseImageRequest proto.InternalMessageInfo

func (m *HostHouseImageRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *HostHouseImageRequest) GetImageData() [][]byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

type HostHouseImageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostHouseImageResponse) Reset()         { *m = HostHouseImageResponse{} }
func (m *HostHouseImageResponse) String() string { return proto.CompactTextString(m) }
func (*HostHouseImageResponse) ProtoMessage()    {}
func (*HostHouseImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{30}
}

func (m *HostHouseImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostHouseImageResponse.Unmarshal(m, b)
}
func (m *HostHouseImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostHouseImageResponse.Marshal(b, m, deterministic)
}
func (m *HostHouseImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostHouseImageResponse.Merge(m, src)
}
func (m *HostHouseImageResponse) XXX_Size() int {
	return xxx_messageInfo_HostHouseImageResponse.Size(m)
}
func (m *HostHouseImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostHouseImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostHouseImageResponse proto.InternalMessageInfo

func (m *HostHouseImageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HostInfoForCreatePostRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AnnouncementId       int32    `protobuf:"varint,2,opt,name=AnnouncementId,proto3" json:"AnnouncementId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostInfoForCreatePostRequest) Reset()         { *m = HostInfoForCreatePostRequest{} }
func (m *HostInfoForCreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*HostInfoForCreatePostRequest) ProtoMessage()    {}
func (*HostInfoForCreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{31}
}

func (m *HostInfoForCreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfoForCreatePostRequest.Unmarshal(m, b)
}
func (m *HostInfoForCreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfoForCreatePostRequest.Marshal(b, m, deterministic)
}
func (m *HostInfoForCreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfoForCreatePostRequest.Merge(m, src)
}
func (m *HostInfoForCreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_HostInfoForCreatePostRequest.Size(m)
}
func (m *HostInfoForCreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfoForCreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfoForCreatePostRequest proto.InternalMessageInfo

func (m *HostInfoForCreatePostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *HostInfoForCreatePostRequest) GetAnnouncementId() int32 {
	if m != nil {
		return m.AnnouncementId
	}
	return 0
}

type HostInfoForCreatePostResponse struct {
	HostImage            string   `protobuf:"bytes,1,opt,name=HostImage,proto3" json:"HostImage,omitempty"`
	HostUsername         string   `protobuf:"bytes,2,opt,name=HostUsername,proto3" json:"HostUsername,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostInfoForCreatePostResponse) Reset()         { *m = HostInfoForCreatePostResponse{} }
func (m *HostInfoForCreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*HostInfoForCreatePostResponse) ProtoMessage()    {}
func (*HostInfoForCreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{32}
}

func (m *HostInfoForCreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfoForCreatePostResponse.Unmarshal(m, b)
}
func (m *HostInfoForCreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfoForCreatePostResponse.Marshal(b, m, deterministic)
}
func (m *HostInfoForCreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfoForCreatePostResponse.Merge(m, src)
}
func (m *HostInfoForCreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_HostInfoForCreatePostResponse.Size(m)
}
func (m *HostInfoForCreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfoForCreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfoForCreatePostResponse proto.InternalMessageInfo

func (m *HostInfoForCreatePostResponse) GetHostImage() string {
	if m != nil {
		return m.HostImage
	}
	return ""
}

func (m *HostInfoForCreatePostResponse) GetHostUsername() string {
	if m != nil {
		return m.HostUsername
	}
	return ""
}

func (m *HostInfoForCreatePostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UploadBlogImageRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	ImageData            []byte   `protobuf:"bytes,2,opt,name=ImageData,proto3" json:"ImageData,omitempty"`
	BlogID               int32    `protobuf:"varint,3,opt,name=BlogID,proto3" json:"BlogID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadBlogImageRequest) Reset()         { *m = UploadBlogImageRequest{} }
func (m *UploadBlogImageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadBlogImageRequest) ProtoMessage()    {}
func (*UploadBlogImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{33}
}

func (m *UploadBlogImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadBlogImageRequest.Unmarshal(m, b)
}
func (m *UploadBlogImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadBlogImageRequest.Marshal(b, m, deterministic)
}
func (m *UploadBlogImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadBlogImageRequest.Merge(m, src)
}
func (m *UploadBlogImageRequest) XXX_Size() int {
	return xxx_messageInfo_UploadBlogImageRequest.Size(m)
}
func (m *UploadBlogImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadBlogImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadBlogImageRequest proto.InternalMessageInfo

func (m *UploadBlogImageRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UploadBlogImageRequest) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

func (m *UploadBlogImageRequest) GetBlogID() int32 {
	if m != nil {
		return m.BlogID
	}
	return 0
}

type UploadBlogImageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadBlogImageResponse) Reset()         { *m = UploadBlogImageResponse{} }
func (m *UploadBlogImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadBlogImageResponse) ProtoMessage()    {}
func (*UploadBlogImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0080e911b962c5cf, []int{34}
}

func (m *UploadBlogImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadBlogImageResponse.Unmarshal(m, b)
}
func (m *UploadBlogImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadBlogImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadBlogImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadBlogImageResponse.Merge(m, src)
}
func (m *UploadBlogImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadBlogImageResponse.Size(m)
}
func (m *UploadBlogImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadBlogImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadBlogImageResponse proto.InternalMessageInfo

func (m *UploadBlogImageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCardRequest)(nil), "createCardRequest")
	proto.RegisterType((*CreateCardResponse)(nil), "createCardResponse")
	proto.RegisterType((*GetCardRequest)(nil), "getCardRequest")
	proto.RegisterType((*CardRecord)(nil), "CardRecord")
	proto.RegisterType((*GetCardResponse)(nil), "getCardResponse")
	proto.RegisterType((*CreateOfferRequest)(nil), "createOfferRequest")
	proto.RegisterType((*CreateOfferResponse)(nil), "createOfferResponse")
	proto.RegisterType((*GetOfferRequest)(nil), "getOfferRequest")
	proto.RegisterType((*OfferRecord)(nil), "OfferRecord")
	proto.RegisterType((*GetOfferResponse)(nil), "getOfferResponse")
	proto.RegisterType((*GetCardProfileRequest)(nil), "getCardProfileRequest")
	proto.RegisterType((*GetCardProfileResponse)(nil), "getCardProfileResponse")
	proto.RegisterType((*CreatePostRequest)(nil), "createPostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "createPostResponse")
	proto.RegisterType((*PostRecord)(nil), "PostRecord")
	proto.RegisterType((*GetMyPostRequest)(nil), "getMyPostRequest")
	proto.RegisterType((*GetMyPostResponse)(nil), "getMyPostResponse")
	proto.RegisterType((*GetPostHostRequest)(nil), "getPostHostRequest")
	proto.RegisterType((*GetPostHostResponse)(nil), "getPostHostResponse")
	proto.RegisterType((*AcceptOfferRequest)(nil), "acceptOfferRequest")
	proto.RegisterType((*AcceptOfferResponse)(nil), "acceptOfferResponse")
	proto.RegisterType((*RejectOfferRequest)(nil), "rejectOfferRequest")
	proto.RegisterType((*RejectOfferResponse)(nil), "rejectOfferResponse")
	proto.RegisterType((*EditAnnouncementRequest)(nil), "editAnnouncementRequest")
	proto.RegisterType((*EditAnnouncementResponse)(nil), "editAnnouncementResponse")
	proto.RegisterType((*DeleteAnnouncementRequest)(nil), "deleteAnnouncementRequest")
	proto.RegisterType((*DeleteAnnouncementResponse)(nil), "deleteAnnouncementResponse")
	proto.RegisterType((*EditPostRequest)(nil), "editPostRequest")
	proto.RegisterType((*EditPostResponse)(nil), "editPostResponse")
	proto.RegisterType((*HostHouseImageRequest)(nil), "hostHouseImageRequest")
	proto.RegisterType((*HostHouseImageResponse)(nil), "hostHouseImageResponse")
	proto.RegisterType((*HostInfoForCreatePostRequest)(nil), "hostInfoForCreatePostRequest")
	proto.RegisterType((*HostInfoForCreatePostResponse)(nil), "hostInfoForCreatePostResponse")
	proto.RegisterType((*UploadBlogImageRequest)(nil), "uploadBlogImageRequest")
	proto.RegisterType((*UploadBlogImageResponse)(nil), "uploadBlogImageResponse")
}

func init() {
	proto.RegisterFile("announcement.proto", fileDescriptor_0080e911b962c5cf)
}

var fileDescriptor_0080e911b962c5cf = []byte{
	// 1320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x56, 0x92, 0x3a, 0x4d, 0x4e, 0x42, 0x9b, 0x4e, 0xb2, 0xa9, 0xd7, 0x74, 0x57, 0xc1, 0x5a,
	0xa1, 0x0a, 0x55, 0x53, 0xa9, 0xbb, 0xa0, 0x72, 0xd9, 0x36, 0x6d, 0x1a, 0x69, 0xdb, 0x8d, 0xdc,
	0x16, 0x24, 0x90, 0x90, 0xdc, 0x64, 0x92, 0x0d, 0xa4, 0x76, 0xf0, 0x4c, 0x2a, 0x15, 0x9e, 0x82,
	0x87, 0xe0, 0x9e, 0x0b, 0x5e, 0x80, 0x87, 0xe0, 0x92, 0xa7, 0xe0, 0x1e, 0xa1, 0x19, 0x8f, 0x7f,
	0x26, 0x76, 0xfe, 0xb4, 0xad, 0xb8, 0xe1, 0x22, 0x52, 0xce, 0x99, 0x99, 0xe3, 0x39, 0xe7, 0xfb,
	0xce, 0x8f, 0x0d, 0xc8, 0x76, 0x1c, 0x77, 0xe2, 0x74, 0xc9, 0x1d, 0x71, 0x18, 0x1e, 0x7b, 0x2e,
	0x73, 0xcd, 0xbf, 0xb3, 0xb0, 0xd5, 0xf5, 0x88, 0xcd, 0xc8, 0x89, 0xed, 0xf5, 0x2c, 0xf2, 0xe3,
	0x84, 0x50, 0x86, 0x1a, 0x50, 0x3a, 0xea, 0x76, 0x09, 0xa5, 0xd7, 0xee, 0x0f, 0xc4, 0xd1, 0x33,
	0x8d, 0xcc, 0x6e, 0xd1, 0x8a, 0xab, 0xf8, 0x8e, 0x26, 0xa1, 0x5d, 0x6f, 0x38, 0x66, 0x43, 0xd7,
	0xd1, 0xb3, 0xfe, 0x8e, 0x98, 0x0a, 0x61, 0x40, 0x1d, 0x8f, 0xf4, 0x89, 0xe7, 0x91, 0xde, 0x5b,
	0xdb, 0x19, 0x4c, 0xec, 0x01, 0xa1, 0x7a, 0xae, 0x91, 0xdb, 0x2d, 0x5a, 0x29, 0x2b, 0x68, 0x07,
	0x8a, 0x57, 0xcc, 0xf6, 0x58, 0xd3, 0x66, 0x44, 0x5f, 0x13, 0xf6, 0x22, 0x05, 0xd2, 0x61, 0xfd,
	0xd4, 0xe9, 0x89, 0x35, 0x4d, 0xac, 0x05, 0x22, 0xda, 0x85, 0xcd, 0x26, 0xa1, 0x6c, 0xe8, 0xd8,
	0xfc, 0xb1, 0x27, 0x43, 0xf6, 0xa0, 0xe7, 0xc5, 0x8e, 0x69, 0x35, 0xfa, 0x0c, 0x2a, 0x31, 0xd5,
	0x15, 0xe3, 0xc6, 0xd6, 0xc5, 0xd6, 0x84, 0x9e, 0xdf, 0x3e, 0x7e, 0xdc, 0x9d, 0x38, 0xcc, 0x7b,
	0xd0, 0x0b, 0x62, 0x77, 0xca, 0x0a, 0xda, 0x83, 0xad, 0xcb, 0xc9, 0xdd, 0x2d, 0xf1, 0xde, 0xf5,
	0xaf, 0x3d, 0xfb, 0x9e, 0x8c, 0x88, 0x47, 0xf5, 0x62, 0x23, 0xb3, 0xab, 0x59, 0xc9, 0x05, 0x13,
	0x03, 0x8a, 0x07, 0x9d, 0x8e, 0x5d, 0x87, 0x0a, 0x1f, 0x2f, 0x08, 0xa5, 0xf6, 0x80, 0xc8, 0x88,
	0x07, 0xa2, 0xf9, 0x5b, 0x06, 0x36, 0x06, 0x84, 0xad, 0x06, 0x91, 0x09, 0xe5, 0xb3, 0xe1, 0x88,
	0x11, 0xef, 0x2b, 0x7b, 0x34, 0x21, 0x54, 0x62, 0xa4, 0xe8, 0x44, 0xd0, 0x5d, 0x8f, 0x09, 0x49,
	0xcf, 0xc9, 0xa0, 0x07, 0x0a, 0x64, 0x40, 0xa1, 0x63, 0x0f, 0xc8, 0xd5, 0xf0, 0xa7, 0x00, 0x91,
	0x50, 0x46, 0x2f, 0x01, 0xf8, 0x7f, 0xdf, 0x37, 0x89, 0x49, 0x4c, 0x63, 0xfe, 0x9e, 0x03, 0xf0,
	0xef, 0xdb, 0x75, 0xbd, 0x1e, 0xaa, 0x43, 0x9e, 0x4b, 0xed, 0x9e, 0xb8, 0xa9, 0x66, 0x49, 0x89,
	0xeb, 0x6f, 0x28, 0xf1, 0xda, 0x3d, 0x71, 0x3d, 0xcd, 0x92, 0xd2, 0x34, 0xbf, 0x72, 0xcb, 0xf2,
	0x6b, 0x6d, 0x39, 0x7e, 0x69, 0x73, 0xf8, 0x95, 0x5f, 0xc8, 0xaf, 0xf5, 0xe5, 0xf9, 0x55, 0x58,
	0x89, 0x5f, 0xc5, 0xd5, 0xf8, 0x05, 0x33, 0xf8, 0x85, 0x6a, 0xa0, 0xb5, 0xef, 0x38, 0x8f, 0x4a,
	0xc2, 0xa0, 0x2f, 0x70, 0x42, 0xf0, 0xe8, 0xf2, 0x9f, 0x63, 0xdf, 0x11, 0xbd, 0xec, 0x13, 0x22,
	0xae, 0x33, 0x47, 0xb0, 0x19, 0x12, 0x4d, 0xd2, 0xf2, 0x13, 0xd0, 0xb8, 0x4c, 0xf5, 0x4c, 0x23,
	0xb7, 0x5b, 0x3a, 0x28, 0xe1, 0x08, 0x56, 0xcb, 0x5f, 0x89, 0x33, 0x37, 0xab, 0x30, 0x97, 0x47,
	0x9d, 0x93, 0x42, 0xb8, 0x21, 0x50, 0xd4, 0xac, 0x48, 0x61, 0x7e, 0x17, 0xe4, 0xc1, 0xbb, 0x7e,
	0x9f, 0x78, 0xcb, 0x53, 0xfb, 0x53, 0xd8, 0x38, 0x8a, 0xd5, 0xb2, 0x90, 0x3d, 0x53, 0x5a, 0x73,
	0x1f, 0xaa, 0x8a, 0xfd, 0x85, 0x89, 0xf6, 0xad, 0x70, 0xff, 0x89, 0x6e, 0xf3, 0x47, 0x06, 0x4a,
	0xd2, 0x74, 0x90, 0x13, 0xe7, 0x2e, 0x65, 0x51, 0x4e, 0xf8, 0x12, 0x7a, 0x05, 0x1f, 0xf1, 0x7f,
	0x67, 0x43, 0x8f, 0xb2, 0x4b, 0x0e, 0x94, 0x1f, 0x53, 0x55, 0xc9, 0xd1, 0xe4, 0x8a, 0xb7, 0xb6,
	0xdc, 0xe4, 0xa7, 0x88, 0xa2, 0x0b, 0xf6, 0x84, 0x88, 0xaf, 0x45, 0x7b, 0x02, 0x5d, 0xc4, 0x15,
	0x2d, 0xce, 0x95, 0x3a, 0xe4, 0x29, 0xb3, 0xd9, 0x84, 0x8a, 0x74, 0xd0, 0x2c, 0x29, 0x99, 0x16,
	0x54, 0xa2, 0x00, 0xc9, 0x70, 0xbe, 0x82, 0xbc, 0xcb, 0x15, 0x01, 0x43, 0xca, 0x38, 0xe6, 0xa5,
	0x25, 0xd7, 0x66, 0x73, 0xc4, 0xfc, 0x12, 0x9e, 0x49, 0xce, 0x75, 0x3c, 0xb7, 0x3f, 0x1c, 0x91,
	0xa5, 0x43, 0x6f, 0xde, 0x40, 0x7d, 0xfa, 0xe8, 0x23, 0xb0, 0xd6, 0xfc, 0x33, 0x13, 0x74, 0xc5,
	0x8e, 0x4b, 0xd9, 0xa3, 0x33, 0x41, 0x64, 0x85, 0x4b, 0xd9, 0xf5, 0x90, 0x8d, 0xc2, 0xb2, 0x1b,
	0x2a, 0x78, 0x69, 0xe5, 0x08, 0x59, 0x36, 0x1b, 0x3a, 0x03, 0x81, 0x99, 0x66, 0xc5, 0x34, 0xa2,
	0x2c, 0xbb, 0x94, 0x1d, 0xbb, 0xbd, 0x07, 0x09, 0x5a, 0x28, 0x73, 0xcb, 0x02, 0xc0, 0xa6, 0xcd,
	0x6c, 0x01, 0x5d, 0xd9, 0x8a, 0x14, 0x51, 0xdf, 0xf1, 0xdd, 0x5a, 0x98, 0x0e, 0xff, 0x64, 0x01,
	0xfc, 0xad, 0x01, 0x61, 0x3b, 0x0a, 0x61, 0x7d, 0x69, 0x69, 0xb7, 0x23, 0xc2, 0xe7, 0x14, 0xc2,
	0x2f, 0x43, 0xd3, 0x1d, 0x28, 0x8a, 0xdd, 0x31, 0xaa, 0x46, 0x0a, 0xee, 0x42, 0x8b, 0x63, 0xd4,
	0xee, 0x49, 0xbe, 0x06, 0x22, 0x4f, 0x26, 0xf1, 0x37, 0x34, 0xee, 0x17, 0x6f, 0x55, 0xc9, 0x43,
	0xee, 0x1f, 0x10, 0xe6, 0xfd, 0xa2, 0x1d, 0xd3, 0xa8, 0x80, 0x15, 0xe7, 0x03, 0x06, 0x73, 0x01,
	0x2b, 0x25, 0x01, 0xeb, 0x84, 0x7e, 0x95, 0x23, 0xcb, 0x42, 0x61, 0xbe, 0x11, 0xe9, 0x76, 0xf1,
	0xb0, 0x12, 0x0d, 0xcd, 0x0e, 0x6c, 0xc5, 0x4e, 0x45, 0x09, 0x31, 0x76, 0x29, 0x8b, 0x12, 0x22,
	0x02, 0xd6, 0xf2, 0x57, 0xe6, 0x24, 0xc4, 0x25, 0xa0, 0x01, 0x61, 0xfc, 0xc4, 0xf9, 0x4a, 0x09,
	0x11, 0x21, 0x9e, 0x8d, 0x23, 0x6e, 0x5a, 0x50, 0x55, 0xec, 0x3d, 0xc6, 0x1d, 0xef, 0x01, 0xd9,
	0xdd, 0x2e, 0x19, 0x3f, 0x51, 0xf9, 0x9e, 0xc5, 0x5e, 0xde, 0x64, 0x94, 0xe7, 0x2e, 0xcc, 0xaa,
	0x7b, 0x40, 0x1e, 0xf9, 0x9e, 0x74, 0xff, 0x83, 0x8b, 0x2a, 0xcf, 0x5d, 0x78, 0xd1, 0x5f, 0x72,
	0xb0, 0x4d, 0x7a, 0x43, 0x16, 0xb7, 0xbf, 0x12, 0xf6, 0x72, 0xe4, 0xcb, 0x2a, 0x23, 0xdf, 0xff,
	0xa3, 0xdd, 0x07, 0x8c, 0x76, 0xe6, 0x1b, 0xd0, 0x93, 0x90, 0x2c, 0x44, 0xf2, 0x06, 0x9e, 0xf7,
	0xc8, 0x88, 0x30, 0xf2, 0xa8, 0x50, 0x9a, 0x5f, 0x80, 0x91, 0x66, 0x76, 0xe1, 0x75, 0x7e, 0xcd,
	0xc0, 0x26, 0xf7, 0xa2, 0xb3, 0x6a, 0x31, 0xe9, 0x28, 0xc5, 0x44, 0xb6, 0x9f, 0x27, 0xeb, 0xa6,
	0xe6, 0x1e, 0x54, 0xa2, 0x6b, 0x2e, 0xf4, 0xea, 0x6b, 0x78, 0xf6, 0x5e, 0x54, 0xb4, 0x09, 0x25,
	0xa2, 0x7c, 0x2f, 0xef, 0x9a, 0xd2, 0xb6, 0xb3, 0x8d, 0x9c, 0xda, 0xb6, 0x0f, 0xa0, 0x3e, 0x6d,
	0x78, 0xe1, 0x65, 0xde, 0xc3, 0x0e, 0x3f, 0xd3, 0x76, 0xfa, 0xee, 0x99, 0xeb, 0x9d, 0x3c, 0xdd,
	0x30, 0x63, 0xfe, 0x0c, 0x2f, 0x66, 0x3c, 0x49, 0x5e, 0x52, 0x69, 0xdd, 0x99, 0xe9, 0xd6, 0x3d,
	0xdd, 0xfc, 0xb3, 0x29, 0xcd, 0x3f, 0xe6, 0x66, 0x4e, 0x75, 0x73, 0x0c, 0xf5, 0xc9, 0x78, 0xe4,
	0xda, 0xbd, 0xe3, 0x91, 0x3b, 0xf8, 0xb0, 0xa0, 0xab, 0xb3, 0x12, 0x67, 0x9b, 0xb0, 0xd9, 0x0c,
	0xaa, 0xa8, 0x2f, 0x99, 0xaf, 0x61, 0x3b, 0xf1, 0xc4, 0x45, 0x68, 0x1c, 0xfc, 0xb5, 0x0e, 0xe5,
	0x78, 0xd8, 0xd0, 0xe7, 0x00, 0x27, 0xe1, 0x17, 0x00, 0x84, 0x70, 0xe2, 0x1b, 0x8c, 0x51, 0xc5,
	0x29, 0x9f, 0x08, 0xf6, 0x60, 0xbd, 0xe5, 0xcf, 0xbb, 0x68, 0x13, 0xab, 0x5f, 0x04, 0x8c, 0x0a,
	0x9e, 0x7e, 0x73, 0x3b, 0x84, 0xd2, 0x49, 0xf4, 0xfa, 0x83, 0x02, 0x8b, 0xf1, 0xb6, 0x63, 0xd4,
	0x70, 0xda, 0x1b, 0xd2, 0x3e, 0x14, 0x5a, 0x72, 0xcc, 0x47, 0xc2, 0xae, 0x72, 0x66, 0x0b, 0x27,
	0xde, 0x01, 0x8e, 0x60, 0xa3, 0xa5, 0x0c, 0xe2, 0xa8, 0x8e, 0x53, 0x87, 0x7a, 0x63, 0x1b, 0xcf,
	0x98, 0xd8, 0xc3, 0x90, 0x70, 0xf2, 0x84, 0x21, 0x89, 0x71, 0x36, 0x0c, 0x89, 0xc2, 0xae, 0x03,
	0x28, 0xb6, 0x82, 0x61, 0x07, 0x89, 0x9b, 0x29, 0xe3, 0x92, 0x81, 0x70, 0x72, 0x16, 0x3a, 0x84,
	0x52, 0x2b, 0x1a, 0x3f, 0x50, 0x15, 0x27, 0x87, 0x1b, 0xa3, 0x86, 0xd3, 0x26, 0x94, 0x43, 0x9f,
	0x55, 0xb2, 0xd9, 0xa3, 0x2a, 0x4e, 0x8e, 0x1c, 0x46, 0x0d, 0xa7, 0xcd, 0x03, 0x87, 0x50, 0xb2,
	0xa2, 0xee, 0x8b, 0xaa, 0x38, 0x39, 0x03, 0x18, 0x35, 0x9c, 0xd6, 0xa0, 0x5b, 0x50, 0x39, 0x9d,
	0x2a, 0xf9, 0x48, 0xc7, 0x33, 0x1a, 0xb3, 0xf1, 0x1c, 0xcf, 0xec, 0x0f, 0x17, 0xbc, 0x33, 0x4d,
	0x97, 0x6b, 0x64, 0xe0, 0x99, 0xad, 0xc1, 0xf8, 0x18, 0xcf, 0xa9, 0xef, 0xfb, 0x50, 0x38, 0x95,
	0xd5, 0x11, 0x55, 0xf0, 0x54, 0x3d, 0x37, 0xb6, 0x70, 0xa2, 0x74, 0xb6, 0xa0, 0x76, 0x23, 0x52,
	0xe7, 0x5c, 0xa9, 0x66, 0xa8, 0x8e, 0x53, 0xeb, 0xa6, 0xb1, 0x8d, 0x67, 0x94, 0xbd, 0x36, 0x14,
	0xce, 0x65, 0xc9, 0x41, 0x2f, 0xf0, 0xbc, 0x3a, 0x67, 0xbc, 0xc4, 0xf3, 0x8b, 0x53, 0x13, 0x36,
	0x6f, 0xd4, 0x74, 0x46, 0xdb, 0x38, 0xbd, 0xa4, 0x18, 0x3a, 0x9e, 0x91, 0xf9, 0xc7, 0xda, 0x37,
	0xb9, 0xfd, 0xf1, 0xed, 0x6d, 0x5e, 0x7c, 0x54, 0x7d, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xe8, 0x19, 0x82, 0xa7, 0x6a, 0x15, 0x00, 0x00,
}
