// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userprofile.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProfileDetailsResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate            string   `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	Country              string   `protobuf:"bytes,7,opt,name=Country,proto3" json:"Country,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Bio                  string   `protobuf:"bytes,9,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Message              string   `protobuf:"bytes,10,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDetailsResponse) Reset()         { *m = ProfileDetailsResponse{} }
func (m *ProfileDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileDetailsResponse) ProtoMessage()    {}
func (*ProfileDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{0}
}

func (m *ProfileDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDetailsResponse.Unmarshal(m, b)
}
func (m *ProfileDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDetailsResponse.Marshal(b, m, deterministic)
}
func (m *ProfileDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDetailsResponse.Merge(m, src)
}
func (m *ProfileDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileDetailsResponse.Size(m)
}
func (m *ProfileDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDetailsResponse proto.InternalMessageInfo

func (m *ProfileDetailsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileDetailsResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *ProfileDetailsResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileDetailsResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProfileDetailsResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *ProfileDetailsResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *ProfileDetailsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProfileDetailsRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDetailsRequest) Reset()         { *m = ProfileDetailsRequest{} }
func (m *ProfileDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileDetailsRequest) ProtoMessage()    {}
func (*ProfileDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{1}
}

func (m *ProfileDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDetailsRequest.Unmarshal(m, b)
}
func (m *ProfileDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDetailsRequest.Marshal(b, m, deterministic)
}
func (m *ProfileDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDetailsRequest.Merge(m, src)
}
func (m *ProfileDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileDetailsRequest.Size(m)
}
func (m *ProfileDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDetailsRequest proto.InternalMessageInfo

func (m *ProfileDetailsRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type EditProfileRequest struct {
	CurrentPassword      string   `protobuf:"bytes,1,opt,name=CurrentPassword,proto3" json:"CurrentPassword,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=Country,proto3" json:"Country,omitempty"`
	Bio                  string   `protobuf:"bytes,6,opt,name=Bio,proto3" json:"Bio,omitempty"`
	NewPassword          string   `protobuf:"bytes,7,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	AccessToken          string   `protobuf:"bytes,8,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileRequest) Reset()         { *m = EditProfileRequest{} }
func (m *EditProfileRequest) String() string { return proto.CompactTextString(m) }
func (*EditProfileRequest) ProtoMessage()    {}
func (*EditProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{2}
}

func (m *EditProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileRequest.Unmarshal(m, b)
}
func (m *EditProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileRequest.Marshal(b, m, deterministic)
}
func (m *EditProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileRequest.Merge(m, src)
}
func (m *EditProfileRequest) XXX_Size() int {
	return xxx_messageInfo_EditProfileRequest.Size(m)
}
func (m *EditProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileRequest proto.InternalMessageInfo

func (m *EditProfileRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *EditProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EditProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EditProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *EditProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *EditProfileRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *EditProfileRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *EditProfileRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type EditProfileResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileResponse) Reset()         { *m = EditProfileResponse{} }
func (m *EditProfileResponse) String() string { return proto.CompactTextString(m) }
func (*EditProfileResponse) ProtoMessage()    {}
func (*EditProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{3}
}

func (m *EditProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileResponse.Unmarshal(m, b)
}
func (m *EditProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileResponse.Marshal(b, m, deterministic)
}
func (m *EditProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileResponse.Merge(m, src)
}
func (m *EditProfileResponse) XXX_Size() int {
	return xxx_messageInfo_EditProfileResponse.Size(m)
}
func (m *EditProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileResponse proto.InternalMessageInfo

func (m *EditProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfileDetailsResponse)(nil), "profileDetailsResponse")
	proto.RegisterType((*ProfileDetailsRequest)(nil), "profileDetailsRequest")
	proto.RegisterType((*EditProfileRequest)(nil), "editProfileRequest")
	proto.RegisterType((*EditProfileResponse)(nil), "editProfileResponse")
}

func init() {
	proto.RegisterFile("userprofile.proto", fileDescriptor_cb4f6db3d15f8caf)
}

var fileDescriptor_cb4f6db3d15f8caf = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4f, 0x6f, 0xe2, 0x30,
	0x10, 0xc5, 0x15, 0x42, 0x02, 0x4c, 0xa4, 0xfd, 0x63, 0x58, 0xd6, 0x42, 0x7b, 0x88, 0x38, 0x71,
	0x0a, 0xd2, 0xee, 0x65, 0x7b, 0xe4, 0x5f, 0x7b, 0x69, 0x11, 0x42, 0xed, 0xa5, 0xb7, 0x00, 0xd3,
	0xd6, 0x2a, 0xc4, 0xa9, 0xed, 0x08, 0xf1, 0x15, 0x7a, 0xee, 0xc7, 0xed, 0xa1, 0x8a, 0xe3, 0x00,
	0x09, 0xb4, 0x37, 0xbf, 0x37, 0x79, 0xd6, 0xcc, 0xcf, 0x13, 0xf8, 0x99, 0x48, 0x14, 0xb1, 0xe0,
	0x0f, 0x6c, 0x8d, 0x41, 0x2c, 0xb8, 0xe2, 0xdd, 0xb7, 0x0a, 0xb4, 0x8d, 0x33, 0x46, 0x15, 0xb2,
	0xb5, 0x9c, 0xa3, 0x8c, 0x79, 0x24, 0x91, 0xb4, 0xc0, 0x99, 0x6c, 0x42, 0xb6, 0xa6, 0x96, 0x6f,
	0xf5, 0x1a, 0xf3, 0x4c, 0x90, 0x0e, 0xd4, 0xef, 0x24, 0x8a, 0x69, 0xb8, 0x41, 0x5a, 0xd1, 0x85,
	0xbd, 0x26, 0x7f, 0xa0, 0x71, 0xc9, 0x84, 0x54, 0xba, 0x68, 0xeb, 0xe2, 0xc1, 0x48, 0x93, 0xd7,
	0xa1, 0x29, 0x56, 0xb3, 0x64, 0xae, 0xd3, 0xe4, 0x90, 0x09, 0xf5, 0x34, 0x0e, 0x15, 0x52, 0x27,
	0x4b, 0xee, 0x0d, 0x42, 0xa0, 0x3a, 0x62, 0x6a, 0x47, 0x5d, 0x5d, 0xd0, 0x67, 0x42, 0xa1, 0x36,
	0xe2, 0x49, 0xa4, 0xc4, 0x8e, 0xd6, 0xb4, 0x9d, 0x4b, 0xd2, 0x06, 0xf7, 0x0a, 0xa3, 0x15, 0x0a,
	0x5a, 0xf7, 0xad, 0x9e, 0x33, 0x37, 0x8a, 0xfc, 0x00, 0x7b, 0xc8, 0x38, 0x6d, 0xe8, 0xaf, 0xd3,
	0x63, 0x7a, 0xc7, 0x0d, 0x4a, 0x19, 0x3e, 0x22, 0x85, 0xec, 0x0e, 0x23, 0xbb, 0x17, 0xf0, 0xab,
	0x4c, 0xe5, 0x25, 0x41, 0xa9, 0x88, 0x0f, 0xde, 0x60, 0xb9, 0x44, 0x29, 0x6f, 0xf9, 0x33, 0x46,
	0x06, 0xcd, 0xb1, 0xd5, 0x7d, 0xb7, 0x80, 0xe0, 0x8a, 0xa9, 0x59, 0x96, 0xcf, 0x83, 0x3d, 0xf8,
	0x3e, 0x4a, 0x84, 0xc0, 0x48, 0xcd, 0x42, 0x29, 0xb7, 0x5c, 0xac, 0x4c, 0xb8, 0x6c, 0x17, 0x29,
	0x56, 0xbe, 0xa2, 0x68, 0x97, 0x28, 0xe6, 0x9c, 0xaa, 0xe7, 0x39, 0x39, 0x45, 0x4e, 0x86, 0x87,
	0x7b, 0xe0, 0xe1, 0x83, 0x37, 0xc5, 0xed, 0xbe, 0xbf, 0x8c, 0xeb, 0xb1, 0x55, 0x1e, 0xbf, 0x7e,
	0x3a, 0x7e, 0x1f, 0x9a, 0x85, 0xe9, 0xcd, 0x32, 0x1d, 0xa1, 0xb6, 0x0a, 0xa8, 0xff, 0xbe, 0x5a,
	0xe0, 0xa5, 0x1b, 0x64, 0x12, 0x64, 0x00, 0xdf, 0x66, 0x05, 0xf4, 0xa4, 0x1d, 0x9c, 0x7d, 0x8b,
	0xce, 0xef, 0xe0, 0x93, 0xcd, 0xfd, 0x0f, 0xde, 0xe4, 0xd0, 0x03, 0x69, 0x06, 0xa7, 0xef, 0xd1,
	0x69, 0x05, 0x67, 0xda, 0x1c, 0x3a, 0xf7, 0x76, 0x3f, 0x5e, 0x2c, 0x5c, 0xfd, 0x73, 0xfc, 0xfb,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x26, 0x51, 0x8e, 0xec, 0x31, 0x03, 0x00, 0x00,
}
