// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userprofile.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProfileDetailsRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDetailsRequest) Reset()         { *m = ProfileDetailsRequest{} }
func (m *ProfileDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileDetailsRequest) ProtoMessage()    {}
func (*ProfileDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{0}
}

func (m *ProfileDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDetailsRequest.Unmarshal(m, b)
}
func (m *ProfileDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDetailsRequest.Marshal(b, m, deterministic)
}
func (m *ProfileDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDetailsRequest.Merge(m, src)
}
func (m *ProfileDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileDetailsRequest.Size(m)
}
func (m *ProfileDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDetailsRequest proto.InternalMessageInfo

func (m *ProfileDetailsRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ProfileDetailsResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate            string   `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=State,proto3" json:"State,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	Gender               int32    `protobuf:"varint,9,opt,name=Gender,proto3" json:"Gender,omitempty"`
	JoiningDate          string   `protobuf:"bytes,10,opt,name=JoiningDate,proto3" json:"JoiningDate,omitempty"`
	Bio                  string   `protobuf:"bytes,11,opt,name=Bio,proto3" json:"Bio,omitempty"`
	IsHost               string   `protobuf:"bytes,12,opt,name=IsHost,proto3" json:"IsHost,omitempty"`
	Address              string   `protobuf:"bytes,13,opt,name=Address,proto3" json:"Address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,14,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	IsPetFriendly        string   `protobuf:"bytes,15,opt,name=IsPetFriendly,proto3" json:"IsPetFriendly,omitempty"`
	IsKidFriendly        string   `protobuf:"bytes,16,opt,name=IsKidFriendly,proto3" json:"IsKidFriendly,omitempty"`
	IsSmokingAllowed     string   `protobuf:"bytes,17,opt,name=IsSmokingAllowed,proto3" json:"IsSmokingAllowed,omitempty"`
	RoomNumber           int32    `protobuf:"varint,18,opt,name=RoomNumber,proto3" json:"RoomNumber,omitempty"`
	Image                string   `protobuf:"bytes,19,opt,name=image,proto3" json:"image,omitempty"`
	Message              string   `protobuf:"bytes,20,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDetailsResponse) Reset()         { *m = ProfileDetailsResponse{} }
func (m *ProfileDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileDetailsResponse) ProtoMessage()    {}
func (*ProfileDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{1}
}

func (m *ProfileDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDetailsResponse.Unmarshal(m, b)
}
func (m *ProfileDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDetailsResponse.Marshal(b, m, deterministic)
}
func (m *ProfileDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDetailsResponse.Merge(m, src)
}
func (m *ProfileDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileDetailsResponse.Size(m)
}
func (m *ProfileDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDetailsResponse proto.InternalMessageInfo

func (m *ProfileDetailsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileDetailsResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *ProfileDetailsResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileDetailsResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProfileDetailsResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProfileDetailsResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *ProfileDetailsResponse) GetJoiningDate() string {
	if m != nil {
		return m.JoiningDate
	}
	return ""
}

func (m *ProfileDetailsResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *ProfileDetailsResponse) GetIsHost() string {
	if m != nil {
		return m.IsHost
	}
	return ""
}

func (m *ProfileDetailsResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProfileDetailsResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *ProfileDetailsResponse) GetIsPetFriendly() string {
	if m != nil {
		return m.IsPetFriendly
	}
	return ""
}

func (m *ProfileDetailsResponse) GetIsKidFriendly() string {
	if m != nil {
		return m.IsKidFriendly
	}
	return ""
}

func (m *ProfileDetailsResponse) GetIsSmokingAllowed() string {
	if m != nil {
		return m.IsSmokingAllowed
	}
	return ""
}

func (m *ProfileDetailsResponse) GetRoomNumber() int32 {
	if m != nil {
		return m.RoomNumber
	}
	return 0
}

func (m *ProfileDetailsResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ProfileDetailsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EditProfileRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	CurrentPassword      string   `protobuf:"bytes,2,opt,name=CurrentPassword,proto3" json:"CurrentPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=LastName,proto3" json:"LastName,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=State,proto3" json:"State,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	Bio                  string   `protobuf:"bytes,9,opt,name=Bio,proto3" json:"Bio,omitempty"`
	IsHost               string   `protobuf:"bytes,10,opt,name=IsHost,proto3" json:"IsHost,omitempty"`
	Address              string   `protobuf:"bytes,11,opt,name=Address,proto3" json:"Address,omitempty"`
	IsPetFriendly        string   `protobuf:"bytes,12,opt,name=IsPetFriendly,proto3" json:"IsPetFriendly,omitempty"`
	IsKidFriendly        string   `protobuf:"bytes,13,opt,name=IsKidFriendly,proto3" json:"IsKidFriendly,omitempty"`
	IsSmokingAllowed     string   `protobuf:"bytes,14,opt,name=IsSmokingAllowed,proto3" json:"IsSmokingAllowed,omitempty"`
	RoomNumber           int32    `protobuf:"varint,15,opt,name=RoomNumber,proto3" json:"RoomNumber,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,16,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileRequest) Reset()         { *m = EditProfileRequest{} }
func (m *EditProfileRequest) String() string { return proto.CompactTextString(m) }
func (*EditProfileRequest) ProtoMessage()    {}
func (*EditProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{2}
}

func (m *EditProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileRequest.Unmarshal(m, b)
}
func (m *EditProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileRequest.Marshal(b, m, deterministic)
}
func (m *EditProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileRequest.Merge(m, src)
}
func (m *EditProfileRequest) XXX_Size() int {
	return xxx_messageInfo_EditProfileRequest.Size(m)
}
func (m *EditProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileRequest proto.InternalMessageInfo

func (m *EditProfileRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *EditProfileRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *EditProfileRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *EditProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EditProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EditProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *EditProfileRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *EditProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *EditProfileRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *EditProfileRequest) GetIsHost() string {
	if m != nil {
		return m.IsHost
	}
	return ""
}

func (m *EditProfileRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EditProfileRequest) GetIsPetFriendly() string {
	if m != nil {
		return m.IsPetFriendly
	}
	return ""
}

func (m *EditProfileRequest) GetIsKidFriendly() string {
	if m != nil {
		return m.IsKidFriendly
	}
	return ""
}

func (m *EditProfileRequest) GetIsSmokingAllowed() string {
	if m != nil {
		return m.IsSmokingAllowed
	}
	return ""
}

func (m *EditProfileRequest) GetRoomNumber() int32 {
	if m != nil {
		return m.RoomNumber
	}
	return 0
}

func (m *EditProfileRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type EditProfileResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileResponse) Reset()         { *m = EditProfileResponse{} }
func (m *EditProfileResponse) String() string { return proto.CompactTextString(m) }
func (*EditProfileResponse) ProtoMessage()    {}
func (*EditProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{3}
}

func (m *EditProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileResponse.Unmarshal(m, b)
}
func (m *EditProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileResponse.Marshal(b, m, deterministic)
}
func (m *EditProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileResponse.Merge(m, src)
}
func (m *EditProfileResponse) XXX_Size() int {
	return xxx_messageInfo_EditProfileResponse.Size(m)
}
func (m *EditProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileResponse proto.InternalMessageInfo

func (m *EditProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ImageRequest struct {
	ImageData            []byte   `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageRequest) Reset()         { *m = ImageRequest{} }
func (m *ImageRequest) String() string { return proto.CompactTextString(m) }
func (*ImageRequest) ProtoMessage()    {}
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{4}
}

func (m *ImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageRequest.Unmarshal(m, b)
}
func (m *ImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageRequest.Marshal(b, m, deterministic)
}
func (m *ImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageRequest.Merge(m, src)
}
func (m *ImageRequest) XXX_Size() int {
	return xxx_messageInfo_ImageRequest.Size(m)
}
func (m *ImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageRequest proto.InternalMessageInfo

func (m *ImageRequest) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

func (m *ImageRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ImageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageResponse) Reset()         { *m = ImageResponse{} }
func (m *ImageResponse) String() string { return proto.CompactTextString(m) }
func (*ImageResponse) ProtoMessage()    {}
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{5}
}

func (m *ImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageResponse.Unmarshal(m, b)
}
func (m *ImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageResponse.Marshal(b, m, deterministic)
}
func (m *ImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageResponse.Merge(m, src)
}
func (m *ImageResponse) XXX_Size() int {
	return xxx_messageInfo_ImageResponse.Size(m)
}
func (m *ImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImageResponse proto.InternalMessageInfo

func (m *ImageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PublicProfileRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicProfileRequest) Reset()         { *m = PublicProfileRequest{} }
func (m *PublicProfileRequest) String() string { return proto.CompactTextString(m) }
func (*PublicProfileRequest) ProtoMessage()    {}
func (*PublicProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{6}
}

func (m *PublicProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicProfileRequest.Unmarshal(m, b)
}
func (m *PublicProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicProfileRequest.Marshal(b, m, deterministic)
}
func (m *PublicProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicProfileRequest.Merge(m, src)
}
func (m *PublicProfileRequest) XXX_Size() int {
	return xxx_messageInfo_PublicProfileRequest.Size(m)
}
func (m *PublicProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicProfileRequest proto.InternalMessageInfo

func (m *PublicProfileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PublicProfileRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type PublicProfileResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate            string   `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=State,proto3" json:"State,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	Gender               int32    `protobuf:"varint,9,opt,name=Gender,proto3" json:"Gender,omitempty"`
	JoiningDate          string   `protobuf:"bytes,10,opt,name=JoiningDate,proto3" json:"JoiningDate,omitempty"`
	Bio                  string   `protobuf:"bytes,11,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Image                string   `protobuf:"bytes,12,opt,name=Image,proto3" json:"Image,omitempty"`
	Message              string   `protobuf:"bytes,13,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicProfileResponse) Reset()         { *m = PublicProfileResponse{} }
func (m *PublicProfileResponse) String() string { return proto.CompactTextString(m) }
func (*PublicProfileResponse) ProtoMessage()    {}
func (*PublicProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{7}
}

func (m *PublicProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicProfileResponse.Unmarshal(m, b)
}
func (m *PublicProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicProfileResponse.Marshal(b, m, deterministic)
}
func (m *PublicProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicProfileResponse.Merge(m, src)
}
func (m *PublicProfileResponse) XXX_Size() int {
	return xxx_messageInfo_PublicProfileResponse.Size(m)
}
func (m *PublicProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicProfileResponse proto.InternalMessageInfo

func (m *PublicProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PublicProfileResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PublicProfileResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PublicProfileResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PublicProfileResponse) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *PublicProfileResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PublicProfileResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *PublicProfileResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *PublicProfileResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *PublicProfileResponse) GetJoiningDate() string {
	if m != nil {
		return m.JoiningDate
	}
	return ""
}

func (m *PublicProfileResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *PublicProfileResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PublicProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PublicProfileHostRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicProfileHostRequest) Reset()         { *m = PublicProfileHostRequest{} }
func (m *PublicProfileHostRequest) String() string { return proto.CompactTextString(m) }
func (*PublicProfileHostRequest) ProtoMessage()    {}
func (*PublicProfileHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{8}
}

func (m *PublicProfileHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicProfileHostRequest.Unmarshal(m, b)
}
func (m *PublicProfileHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicProfileHostRequest.Marshal(b, m, deterministic)
}
func (m *PublicProfileHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicProfileHostRequest.Merge(m, src)
}
func (m *PublicProfileHostRequest) XXX_Size() int {
	return xxx_messageInfo_PublicProfileHostRequest.Size(m)
}
func (m *PublicProfileHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicProfileHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicProfileHostRequest proto.InternalMessageInfo

func (m *PublicProfileHostRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *PublicProfileHostRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type PublicProfileHostResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate            string   `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=State,proto3" json:"State,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	Gender               int32    `protobuf:"varint,9,opt,name=Gender,proto3" json:"Gender,omitempty"`
	JoiningDate          string   `protobuf:"bytes,10,opt,name=JoiningDate,proto3" json:"JoiningDate,omitempty"`
	Bio                  string   `protobuf:"bytes,11,opt,name=Bio,proto3" json:"Bio,omitempty"`
	IsHost               string   `protobuf:"bytes,12,opt,name=IsHost,proto3" json:"IsHost,omitempty"`
	Address              string   `protobuf:"bytes,13,opt,name=Address,proto3" json:"Address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,14,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	IsPetFriendly        string   `protobuf:"bytes,15,opt,name=IsPetFriendly,proto3" json:"IsPetFriendly,omitempty"`
	IsKidFriendly        string   `protobuf:"bytes,16,opt,name=IsKidFriendly,proto3" json:"IsKidFriendly,omitempty"`
	IsSmokingAllowed     string   `protobuf:"bytes,17,opt,name=IsSmokingAllowed,proto3" json:"IsSmokingAllowed,omitempty"`
	RoomNumber           int32    `protobuf:"varint,18,opt,name=RoomNumber,proto3" json:"RoomNumber,omitempty"`
	Image                string   `protobuf:"bytes,19,opt,name=image,proto3" json:"image,omitempty"`
	Message              string   `protobuf:"bytes,20,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicProfileHostResponse) Reset()         { *m = PublicProfileHostResponse{} }
func (m *PublicProfileHostResponse) String() string { return proto.CompactTextString(m) }
func (*PublicProfileHostResponse) ProtoMessage()    {}
func (*PublicProfileHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{9}
}

func (m *PublicProfileHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicProfileHostResponse.Unmarshal(m, b)
}
func (m *PublicProfileHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicProfileHostResponse.Marshal(b, m, deterministic)
}
func (m *PublicProfileHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicProfileHostResponse.Merge(m, src)
}
func (m *PublicProfileHostResponse) XXX_Size() int {
	return xxx_messageInfo_PublicProfileHostResponse.Size(m)
}
func (m *PublicProfileHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicProfileHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicProfileHostResponse proto.InternalMessageInfo

func (m *PublicProfileHostResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PublicProfileHostResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PublicProfileHostResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PublicProfileHostResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PublicProfileHostResponse) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *PublicProfileHostResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PublicProfileHostResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *PublicProfileHostResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *PublicProfileHostResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *PublicProfileHostResponse) GetJoiningDate() string {
	if m != nil {
		return m.JoiningDate
	}
	return ""
}

func (m *PublicProfileHostResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *PublicProfileHostResponse) GetIsHost() string {
	if m != nil {
		return m.IsHost
	}
	return ""
}

func (m *PublicProfileHostResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PublicProfileHostResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *PublicProfileHostResponse) GetIsPetFriendly() string {
	if m != nil {
		return m.IsPetFriendly
	}
	return ""
}

func (m *PublicProfileHostResponse) GetIsKidFriendly() string {
	if m != nil {
		return m.IsKidFriendly
	}
	return ""
}

func (m *PublicProfileHostResponse) GetIsSmokingAllowed() string {
	if m != nil {
		return m.IsSmokingAllowed
	}
	return ""
}

func (m *PublicProfileHostResponse) GetRoomNumber() int32 {
	if m != nil {
		return m.RoomNumber
	}
	return 0
}

func (m *PublicProfileHostResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PublicProfileHostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddChatListRequest struct {
	HostID               int32    `protobuf:"varint,1,opt,name=HostID,proto3" json:"HostID,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddChatListRequest) Reset()         { *m = AddChatListRequest{} }
func (m *AddChatListRequest) String() string { return proto.CompactTextString(m) }
func (*AddChatListRequest) ProtoMessage()    {}
func (*AddChatListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{10}
}

func (m *AddChatListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddChatListRequest.Unmarshal(m, b)
}
func (m *AddChatListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddChatListRequest.Marshal(b, m, deterministic)
}
func (m *AddChatListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddChatListRequest.Merge(m, src)
}
func (m *AddChatListRequest) XXX_Size() int {
	return xxx_messageInfo_AddChatListRequest.Size(m)
}
func (m *AddChatListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddChatListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddChatListRequest proto.InternalMessageInfo

func (m *AddChatListRequest) GetHostID() int32 {
	if m != nil {
		return m.HostID
	}
	return 0
}

func (m *AddChatListRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type AddChatListResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddChatListResponse) Reset()         { *m = AddChatListResponse{} }
func (m *AddChatListResponse) String() string { return proto.CompactTextString(m) }
func (*AddChatListResponse) ProtoMessage()    {}
func (*AddChatListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{11}
}

func (m *AddChatListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddChatListResponse.Unmarshal(m, b)
}
func (m *AddChatListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddChatListResponse.Marshal(b, m, deterministic)
}
func (m *AddChatListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddChatListResponse.Merge(m, src)
}
func (m *AddChatListResponse) XXX_Size() int {
	return xxx_messageInfo_AddChatListResponse.Size(m)
}
func (m *AddChatListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddChatListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddChatListResponse proto.InternalMessageInfo

func (m *AddChatListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChatListRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatListRequest) Reset()         { *m = ChatListRequest{} }
func (m *ChatListRequest) String() string { return proto.CompactTextString(m) }
func (*ChatListRequest) ProtoMessage()    {}
func (*ChatListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{12}
}

func (m *ChatListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatListRequest.Unmarshal(m, b)
}
func (m *ChatListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatListRequest.Marshal(b, m, deterministic)
}
func (m *ChatListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatListRequest.Merge(m, src)
}
func (m *ChatListRequest) XXX_Size() int {
	return xxx_messageInfo_ChatListRequest.Size(m)
}
func (m *ChatListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatListRequest proto.InternalMessageInfo

func (m *ChatListRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ChatList struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	HostID               int32    `protobuf:"varint,2,opt,name=HostID,proto3" json:"HostID,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatList) Reset()         { *m = ChatList{} }
func (m *ChatList) String() string { return proto.CompactTextString(m) }
func (*ChatList) ProtoMessage()    {}
func (*ChatList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{13}
}

func (m *ChatList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatList.Unmarshal(m, b)
}
func (m *ChatList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatList.Marshal(b, m, deterministic)
}
func (m *ChatList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatList.Merge(m, src)
}
func (m *ChatList) XXX_Size() int {
	return xxx_messageInfo_ChatList.Size(m)
}
func (m *ChatList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatList.DiscardUnknown(m)
}

var xxx_messageInfo_ChatList proto.InternalMessageInfo

func (m *ChatList) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ChatList) GetHostID() int32 {
	if m != nil {
		return m.HostID
	}
	return 0
}

func (m *ChatList) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChatList) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ChatListResponse struct {
	Users                []*ChatList `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChatListResponse) Reset()         { *m = ChatListResponse{} }
func (m *ChatListResponse) String() string { return proto.CompactTextString(m) }
func (*ChatListResponse) ProtoMessage()    {}
func (*ChatListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{14}
}

func (m *ChatListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatListResponse.Unmarshal(m, b)
}
func (m *ChatListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatListResponse.Marshal(b, m, deterministic)
}
func (m *ChatListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatListResponse.Merge(m, src)
}
func (m *ChatListResponse) XXX_Size() int {
	return xxx_messageInfo_ChatListResponse.Size(m)
}
func (m *ChatListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatListResponse proto.InternalMessageInfo

func (m *ChatListResponse) GetUsers() []*ChatList {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ChatListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfileDetailsRequest)(nil), "profileDetailsRequest")
	proto.RegisterType((*ProfileDetailsResponse)(nil), "profileDetailsResponse")
	proto.RegisterType((*EditProfileRequest)(nil), "editProfileRequest")
	proto.RegisterType((*EditProfileResponse)(nil), "editProfileResponse")
	proto.RegisterType((*ImageRequest)(nil), "ImageRequest")
	proto.RegisterType((*ImageResponse)(nil), "ImageResponse")
	proto.RegisterType((*PublicProfileRequest)(nil), "publicProfileRequest")
	proto.RegisterType((*PublicProfileResponse)(nil), "publicProfileResponse")
	proto.RegisterType((*PublicProfileHostRequest)(nil), "publicProfileHostRequest")
	proto.RegisterType((*PublicProfileHostResponse)(nil), "publicProfileHostResponse")
	proto.RegisterType((*AddChatListRequest)(nil), "addChatListRequest")
	proto.RegisterType((*AddChatListResponse)(nil), "addChatListResponse")
	proto.RegisterType((*ChatListRequest)(nil), "chatListRequest")
	proto.RegisterType((*ChatList)(nil), "chatList")
	proto.RegisterType((*ChatListResponse)(nil), "chatListResponse")
}

func init() {
	proto.RegisterFile("userprofile.proto", fileDescriptor_cb4f6db3d15f8caf)
}

var fileDescriptor_cb4f6db3d15f8caf = []byte{
	// 867 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x97, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0xc7, 0x85, 0xc1, 0xd9, 0x70, 0x1c, 0x13, 0x32, 0x10, 0x3a, 0x6b, 0xf5, 0x23, 0x42, 0xbd,
	0x48, 0xab, 0x6a, 0x22, 0x65, 0x6f, 0xda, 0x5e, 0x54, 0x22, 0xb0, 0xbb, 0x65, 0xbb, 0x4b, 0x11,
	0x9b, 0x95, 0xaa, 0xde, 0x54, 0x06, 0x4f, 0x93, 0x51, 0x8c, 0x87, 0x7a, 0x06, 0x45, 0x79, 0xaf,
	0x3e, 0x47, 0xa5, 0x3e, 0x42, 0x5f, 0xa4, 0xaa, 0xe6, 0x03, 0x63, 0x1b, 0x68, 0x50, 0xd5, 0xcb,
	0xdc, 0x71, 0xfe, 0x73, 0xce, 0x7c, 0x9c, 0xf9, 0xf9, 0x9c, 0x01, 0x4e, 0x96, 0x82, 0xa6, 0x8b,
	0x94, 0xff, 0xca, 0x62, 0x4a, 0x16, 0x29, 0x97, 0xbc, 0xfb, 0x0d, 0x9c, 0x5a, 0x61, 0x40, 0x65,
	0xc8, 0x62, 0x31, 0xa1, 0xbf, 0x2d, 0xa9, 0x90, 0xe8, 0x0c, 0xbc, 0xde, 0x6c, 0x46, 0x85, 0xb8,
	0xe6, 0x77, 0x34, 0xc1, 0x95, 0xb3, 0xca, 0x79, 0x7d, 0x92, 0x97, 0xba, 0x7f, 0xd4, 0xa0, 0x53,
	0x8e, 0x15, 0x0b, 0x9e, 0x08, 0x8a, 0xda, 0xe0, 0xbe, 0x9c, 0x87, 0x2c, 0xb6, 0x61, 0xc6, 0x40,
	0x01, 0x1c, 0x7e, 0x10, 0x34, 0x1d, 0x85, 0x73, 0x8a, 0x1d, 0x3d, 0x90, 0xd9, 0xe8, 0x63, 0xa8,
	0xbf, 0x62, 0xa9, 0x90, 0x7a, 0xb0, 0xaa, 0x07, 0xd7, 0x82, 0x8a, 0x7c, 0x1b, 0xda, 0xc1, 0x9a,
	0x89, 0x5c, 0xd9, 0x2a, 0xf2, 0x8a, 0xa5, 0xf2, 0x76, 0x10, 0x4a, 0x8a, 0x5d, 0x13, 0x99, 0x09,
	0x08, 0x41, 0xad, 0xcf, 0xe4, 0x03, 0x3e, 0xd0, 0x03, 0xfa, 0xb7, 0xda, 0xdd, 0x7b, 0xa9, 0xbc,
	0x9f, 0x99, 0xdd, 0x69, 0x03, 0x61, 0x78, 0xd6, 0xe7, 0xcb, 0x44, 0xa6, 0x0f, 0xf8, 0x50, 0xeb,
	0x2b, 0x13, 0x75, 0xe0, 0xe0, 0x35, 0x4d, 0x22, 0x9a, 0xe2, 0xfa, 0x59, 0xe5, 0xdc, 0x9d, 0x58,
	0x4b, 0xa5, 0xe8, 0x0d, 0x67, 0x09, 0x4b, 0x6e, 0xf4, 0xda, 0x60, 0x52, 0x94, 0x93, 0x50, 0x13,
	0xaa, 0x57, 0x8c, 0x63, 0x4f, 0x8f, 0xa8, 0x9f, 0x6a, 0xae, 0xa1, 0xf8, 0x9e, 0x0b, 0x89, 0x8f,
	0xb4, 0x68, 0x2d, 0xb5, 0x7a, 0x2f, 0x8a, 0x52, 0x2a, 0x04, 0xf6, 0xcd, 0xea, 0xd6, 0x54, 0xab,
	0x8c, 0x6f, 0x79, 0x42, 0x47, 0xcb, 0xf9, 0x94, 0xa6, 0xb8, 0x61, 0x56, 0xc9, 0x49, 0xe8, 0x73,
	0xf0, 0x87, 0x62, 0x4c, 0xe5, 0xab, 0x94, 0xd1, 0x24, 0x8a, 0x1f, 0xf0, 0xb1, 0xf6, 0x29, 0x8a,
	0xc6, 0xeb, 0x07, 0x16, 0x65, 0x5e, 0xcd, 0x95, 0x57, 0x4e, 0x44, 0x5f, 0x42, 0x73, 0x28, 0xde,
	0xcf, 0xf9, 0x1d, 0x4b, 0x6e, 0x7a, 0x71, 0xcc, 0xef, 0x69, 0x84, 0x4f, 0xb4, 0xe3, 0x86, 0x8e,
	0x3e, 0x05, 0x98, 0x70, 0x3e, 0xb7, 0x1b, 0x43, 0x3a, 0x37, 0x39, 0x45, 0xe5, 0x99, 0xcd, 0xc3,
	0x1b, 0x8a, 0x5b, 0x26, 0xcf, 0xda, 0x50, 0x27, 0x7d, 0x47, 0x85, 0x50, 0x7a, 0xdb, 0x9c, 0xd4,
	0x9a, 0xdd, 0xbf, 0xab, 0x80, 0x68, 0xc4, 0xe4, 0xd8, 0x40, 0xb5, 0x37, 0x89, 0xe8, 0x1c, 0x8e,
	0xfb, 0xcb, 0x34, 0xa5, 0x89, 0x1c, 0x87, 0x42, 0xdc, 0xf3, 0x34, 0xb2, 0x7c, 0x95, 0x65, 0x35,
	0xd7, 0x88, 0xde, 0x67, 0x5e, 0x06, 0xb4, 0xbc, 0x54, 0x04, 0xb1, 0xf6, 0x6f, 0x20, 0xba, 0x25,
	0x10, 0xff, 0x0f, 0xd4, 0x2c, 0x30, 0xf5, 0x6d, 0xc0, 0xc0, 0x2e, 0x60, 0xbc, 0x22, 0x30, 0x1b,
	0x38, 0x1c, 0xed, 0x85, 0x83, 0xbf, 0x2f, 0x0e, 0x8d, 0xbd, 0x70, 0x38, 0xde, 0xc0, 0xa1, 0x04,
	0x72, 0x73, 0x03, 0xe4, 0xee, 0x05, 0xb4, 0x0a, 0xf7, 0x6f, 0xab, 0x49, 0x8e, 0x98, 0x4a, 0x91,
	0x98, 0x1f, 0xe1, 0x68, 0xa8, 0xa0, 0x5a, 0xa1, 0xf2, 0x09, 0x80, 0x86, 0xec, 0x97, 0x28, 0x94,
	0xa1, 0x76, 0x3e, 0x9a, 0xd4, 0xb5, 0x32, 0x08, 0x65, 0x58, 0x26, 0xc9, 0xd9, 0xac, 0x69, 0x5f,
	0x80, 0x6f, 0x27, 0x7c, 0x74, 0xed, 0x6b, 0x68, 0x2f, 0x96, 0xd3, 0x98, 0xcd, 0x4a, 0xb8, 0xda,
	0x2a, 0x97, 0x28, 0x44, 0x2a, 0xeb, 0x2a, 0xa7, 0xec, 0x3d, 0x36, 0xf0, 0x97, 0x03, 0xa7, 0xa5,
	0x69, 0x9f, 0x6a, 0xea, 0x23, 0x35, 0xb5, 0x0d, 0xae, 0xbe, 0x34, 0x0b, 0xba, 0x31, 0xf2, 0x37,
	0xe7, 0x17, 0x6f, 0xee, 0x27, 0xc0, 0x85, 0x14, 0xab, 0xef, 0x69, 0xff, 0x62, 0x93, 0xbf, 0x5f,
	0xa7, 0x78, 0xbf, 0xdd, 0x3f, 0x6b, 0xf0, 0x7c, 0xcb, 0xd4, 0x4f, 0x37, 0xf8, 0xd4, 0x15, 0xff,
	0x73, 0x57, 0x1c, 0x01, 0x0a, 0xa3, 0xa8, 0x7f, 0x1b, 0xca, 0xb7, 0x6c, 0xcd, 0x69, 0x07, 0x0e,
	0x54, 0x86, 0x86, 0x03, 0x0d, 0x93, 0x3b, 0xb1, 0xd6, 0x1e, 0x15, 0xe6, 0x02, 0x5a, 0x85, 0xf9,
	0xd6, 0x85, 0x6e, 0x5e, 0x2c, 0x74, 0xd6, 0xec, 0xbe, 0x80, 0xe3, 0x59, 0x69, 0xf5, 0xc7, 0x1f,
	0x87, 0x11, 0x1c, 0xae, 0x82, 0x50, 0x03, 0x9c, 0x6c, 0x9f, 0xce, 0x70, 0x90, 0xdb, 0xbb, 0x53,
	0xd8, 0x7b, 0x00, 0x87, 0xcb, 0xd5, 0x97, 0x65, 0x60, 0xcf, 0xec, 0x75, 0xd6, 0x6a, 0xb9, 0xac,
	0x75, 0xdf, 0x41, 0x73, 0x56, 0x3e, 0xc8, 0x67, 0xe0, 0xaa, 0x28, 0x81, 0x2b, 0x67, 0xd5, 0x73,
	0xef, 0xb2, 0x4e, 0x32, 0x0f, 0xa3, 0xe7, 0x4f, 0xea, 0x14, 0x4e, 0x7a, 0xf9, 0x7b, 0x15, 0x3c,
	0xf5, 0xed, 0xd9, 0x8f, 0x17, 0xf5, 0xa0, 0x31, 0x2e, 0x3c, 0x70, 0x51, 0x87, 0x6c, 0x7d, 0x2d,
	0x07, 0x1f, 0x91, 0x1d, 0x2f, 0xe1, 0xaf, 0xc1, 0x7b, 0xb9, 0x6e, 0x69, 0xa8, 0x45, 0x36, 0x1f,
	0x38, 0x41, 0x9b, 0x6c, 0xeb, 0x7a, 0x5f, 0x81, 0xf7, 0x61, 0x11, 0xf3, 0x30, 0x32, 0xe5, 0xcc,
	0x27, 0xf9, 0x4e, 0x17, 0x34, 0x48, 0xb1, 0x4f, 0x7d, 0x07, 0xfe, 0x38, 0x5f, 0x78, 0xd0, 0x29,
	0xd9, 0xd6, 0x9d, 0x82, 0x0e, 0xd9, 0xde, 0x5d, 0xde, 0xc0, 0xc9, 0xb8, 0x5c, 0xb8, 0xd0, 0x73,
	0xb2, 0xab, 0x4e, 0x06, 0x01, 0xd9, 0x5d, 0xe7, 0xbe, 0x05, 0xbf, 0x17, 0x45, 0xd7, 0x7c, 0xc5,
	0x18, 0x6a, 0x91, 0x4d, 0x82, 0x83, 0x36, 0xd9, 0x86, 0xe1, 0x25, 0x78, 0xaf, 0xa9, 0xcc, 0x22,
	0x9b, 0xa4, 0x84, 0x5e, 0x70, 0x42, 0xca, 0x37, 0x7e, 0xe5, 0xfe, 0x5c, 0xbd, 0x58, 0x4c, 0xa7,
	0x07, 0xfa, 0x1f, 0xcd, 0x8b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x74, 0x84, 0x80, 0x89, 0xe6,
	0x0c, 0x00, 0x00,
}
