// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate            string   `protobuf:"bytes,6,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	City                 string   `protobuf:"bytes,7,opt,name=City,proto3" json:"City,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	Gender               int32    `protobuf:"varint,9,opt,name=Gender,proto3" json:"Gender,omitempty"`
	IsVerified           bool     `protobuf:"varint,10,opt,name=IsVerified,proto3" json:"IsVerified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{2}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SignUpRequest) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *SignUpRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SignUpRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SignUpRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *SignUpRequest) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

type SignUpResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{3}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RefreshRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{4}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

func (m *RefreshRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshResponse) Reset()         { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()    {}
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{5}
}

func (m *RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResponse.Unmarshal(m, b)
}
func (m *RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResponse.Merge(m, src)
}
func (m *RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshResponse.Size(m)
}
func (m *RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResponse proto.InternalMessageInfo

func (m *RefreshResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RefreshResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ForgetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordRequest) Reset()         { *m = ForgetPasswordRequest{} }
func (m *ForgetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{6}
}

func (m *ForgetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordRequest.Size(m)
}
func (m *ForgetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ForgetPasswordResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordResponse) Reset()         { *m = ForgetPasswordResponse{} }
func (m *ForgetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordResponse) ProtoMessage()    {}
func (*ForgetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{7}
}

func (m *ForgetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordResponse.Unmarshal(m, b)
}
func (m *ForgetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordResponse.Merge(m, src)
}
func (m *ForgetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordResponse.Size(m)
}
func (m *ForgetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordResponse proto.InternalMessageInfo

func (m *ForgetPasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "loginRequest")
	proto.RegisterType((*LoginResponse)(nil), "loginResponse")
	proto.RegisterType((*SignUpRequest)(nil), "SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "SignUpResponse")
	proto.RegisterType((*RefreshRequest)(nil), "refreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "refreshResponse")
	proto.RegisterType((*ForgetPasswordRequest)(nil), "forgetPasswordRequest")
	proto.RegisterType((*ForgetPasswordResponse)(nil), "forgetPasswordResponse")
}

func init() {
	proto.RegisterFile("authentication.proto", fileDescriptor_d0dbc99083440df2)
}

var fileDescriptor_d0dbc99083440df2 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xed, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xda, 0xa6, 0x1f, 0x97, 0x35, 0x45, 0xd6, 0x28, 0x56, 0x84, 0x50, 0xe5, 0x1f, 0xa8,
	0x20, 0x30, 0xd2, 0xe0, 0x01, 0xe8, 0x06, 0x43, 0x48, 0x1b, 0x42, 0x81, 0xf1, 0x83, 0x7f, 0x5e,
	0x7b, 0xdb, 0x5a, 0x6c, 0x76, 0xb0, 0x1d, 0xa1, 0x3d, 0x0b, 0x6f, 0xc4, 0x53, 0xa1, 0x7c, 0x95,
	0x38, 0x9b, 0xd6, 0x7f, 0x39, 0xf7, 0xfa, 0x38, 0xf7, 0x9c, 0x7b, 0x0c, 0x87, 0x22, 0x73, 0x5b,
	0x54, 0x4e, 0x2e, 0x85, 0x93, 0x5a, 0xf1, 0xd4, 0x68, 0xa7, 0xd9, 0x3b, 0x38, 0xb8, 0xd2, 0x1b,
	0xa9, 0x12, 0xfc, 0x95, 0xa1, 0x75, 0xe4, 0x10, 0xc2, 0x0f, 0xd7, 0x42, 0x5e, 0xd1, 0x60, 0x16,
	0xcc, 0x47, 0x49, 0x09, 0x48, 0x0c, 0xc3, 0x2f, 0xc2, 0xda, 0xdf, 0xda, 0xac, 0x68, 0xa7, 0x68,
	0xec, 0x30, 0xd3, 0x30, 0xae, 0x6e, 0xb0, 0xa9, 0x56, 0x16, 0xc9, 0x0c, 0x1e, 0x2c, 0x96, 0x4b,
	0xb4, 0xf6, 0x9b, 0xfe, 0x89, 0xaa, 0xba, 0xa8, 0x59, 0x22, 0x0c, 0x0e, 0x12, 0x5c, 0x1b, 0xb4,
	0xdb, 0xf2, 0x48, 0x79, 0xa5, 0x57, 0x23, 0x14, 0x06, 0xe7, 0x68, 0xad, 0xd8, 0x20, 0xed, 0x16,
	0xed, 0x1a, 0xb2, 0x3f, 0x1d, 0x18, 0x7f, 0x95, 0x1b, 0x75, 0x91, 0xee, 0x1d, 0xfa, 0xc2, 0xa2,
	0xf9, 0x2c, 0xae, 0xb1, 0x1e, 0xba, 0xc6, 0x9e, 0xa0, 0xae, 0x2f, 0x88, 0x3c, 0x81, 0xd1, 0xa9,
	0x34, 0xd6, 0x15, 0xc4, 0x5e, 0xd1, 0xfc, 0x5f, 0xc8, 0x99, 0x67, 0xa2, 0x6a, 0x86, 0x25, 0xb3,
	0xc6, 0x39, 0xf3, 0x58, 0x1a, 0xb7, 0x7d, 0x2f, 0x1c, 0xd2, 0x7e, 0xc9, 0xdc, 0x15, 0x08, 0x81,
	0xde, 0x89, 0x74, 0x37, 0x74, 0x50, 0x34, 0x8a, 0xef, 0x5c, 0xe5, 0x89, 0xce, 0x94, 0x33, 0x37,
	0x74, 0x58, 0xaa, 0xac, 0x20, 0x99, 0x42, 0xff, 0x23, 0xaa, 0x15, 0x1a, 0x3a, 0x9a, 0x05, 0xf3,
	0x30, 0xa9, 0x10, 0x79, 0x0a, 0xf0, 0xc9, 0x7e, 0x47, 0x23, 0xd7, 0x12, 0x57, 0x14, 0x66, 0xc1,
	0x7c, 0x98, 0x34, 0x2a, 0xec, 0x05, 0x44, 0xb5, 0x39, 0xd5, 0x3e, 0x1a, 0x4e, 0x06, 0xbe, 0x93,
	0x6f, 0x21, 0x32, 0xa5, 0xe7, 0xb5, 0x93, 0xed, 0xcd, 0x04, 0xb7, 0x37, 0xc3, 0xce, 0x61, 0xb2,
	0x63, 0xed, 0xfb, 0x45, 0x3b, 0x0c, 0x9d, 0x5b, 0x61, 0x60, 0xaf, 0xe0, 0xd1, 0x5a, 0x9b, 0x0d,
	0xba, 0x7a, 0x01, 0xf7, 0x6e, 0x95, 0x1d, 0xc1, 0xb4, 0x7d, 0x7c, 0xdf, 0x10, 0x47, 0x7f, 0x03,
	0xe8, 0x2d, 0x32, 0xb7, 0x25, 0xcf, 0xa1, 0x9f, 0x9b, 0x93, 0xa5, 0x24, 0xe2, 0x5e, 0x84, 0xe2,
	0x09, 0x6f, 0xb9, 0xf6, 0x0c, 0xc2, 0xb3, 0x3c, 0xd6, 0x64, 0xcc, 0x9b, 0x0f, 0x24, 0x8e, 0xb8,
	0x9f, 0xf6, 0x97, 0x30, 0xa8, 0xdc, 0x21, 0x13, 0xee, 0xbb, 0x19, 0x3f, 0xe4, 0x6d, 0xa3, 0x16,
	0x10, 0x9d, 0x7a, 0xd3, 0x93, 0x29, 0xbf, 0x53, 0x7d, 0xfc, 0x98, 0xdf, 0x2d, 0xf3, 0x38, 0xfc,
	0xd1, 0x7d, 0x9d, 0x5e, 0x5e, 0xf6, 0x8b, 0xf7, 0xfb, 0xe6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb0, 0x84, 0x1d, 0x82, 0xd7, 0x03, 0x00, 0x00,
}
