// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userprofile.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProfileDetailsResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate            string   `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	Country              string   `protobuf:"bytes,7,opt,name=Country,proto3" json:"Country,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Bio                  string   `protobuf:"bytes,9,opt,name=Bio,proto3" json:"Bio,omitempty"`
	State                string   `protobuf:"bytes,10,opt,name=State,proto3" json:"State,omitempty"`
	JoiningDate          string   `protobuf:"bytes,11,opt,name=JoiningDate,proto3" json:"JoiningDate,omitempty"`
	Message              string   `protobuf:"bytes,12,opt,name=Message,proto3" json:"Message,omitempty"`
	Image                string   `protobuf:"bytes,13,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDetailsResponse) Reset()         { *m = ProfileDetailsResponse{} }
func (m *ProfileDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileDetailsResponse) ProtoMessage()    {}
func (*ProfileDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{0}
}

func (m *ProfileDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDetailsResponse.Unmarshal(m, b)
}
func (m *ProfileDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDetailsResponse.Marshal(b, m, deterministic)
}
func (m *ProfileDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDetailsResponse.Merge(m, src)
}
func (m *ProfileDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileDetailsResponse.Size(m)
}
func (m *ProfileDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDetailsResponse proto.InternalMessageInfo

func (m *ProfileDetailsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileDetailsResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileDetailsResponse) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *ProfileDetailsResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileDetailsResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProfileDetailsResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *ProfileDetailsResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *ProfileDetailsResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProfileDetailsResponse) GetJoiningDate() string {
	if m != nil {
		return m.JoiningDate
	}
	return ""
}

func (m *ProfileDetailsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProfileDetailsResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ProfileDetailsRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDetailsRequest) Reset()         { *m = ProfileDetailsRequest{} }
func (m *ProfileDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileDetailsRequest) ProtoMessage()    {}
func (*ProfileDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{1}
}

func (m *ProfileDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDetailsRequest.Unmarshal(m, b)
}
func (m *ProfileDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDetailsRequest.Marshal(b, m, deterministic)
}
func (m *ProfileDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDetailsRequest.Merge(m, src)
}
func (m *ProfileDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileDetailsRequest.Size(m)
}
func (m *ProfileDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDetailsRequest proto.InternalMessageInfo

func (m *ProfileDetailsRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type EditProfileRequest struct {
	CurrentPassword      string   `protobuf:"bytes,1,opt,name=CurrentPassword,proto3" json:"CurrentPassword,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=Country,proto3" json:"Country,omitempty"`
	Bio                  string   `protobuf:"bytes,6,opt,name=Bio,proto3" json:"Bio,omitempty"`
	NewPassword          string   `protobuf:"bytes,7,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	AccessToken          string   `protobuf:"bytes,8,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileRequest) Reset()         { *m = EditProfileRequest{} }
func (m *EditProfileRequest) String() string { return proto.CompactTextString(m) }
func (*EditProfileRequest) ProtoMessage()    {}
func (*EditProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{2}
}

func (m *EditProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileRequest.Unmarshal(m, b)
}
func (m *EditProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileRequest.Marshal(b, m, deterministic)
}
func (m *EditProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileRequest.Merge(m, src)
}
func (m *EditProfileRequest) XXX_Size() int {
	return xxx_messageInfo_EditProfileRequest.Size(m)
}
func (m *EditProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileRequest proto.InternalMessageInfo

func (m *EditProfileRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *EditProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EditProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EditProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *EditProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *EditProfileRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *EditProfileRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *EditProfileRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type EditProfileResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileResponse) Reset()         { *m = EditProfileResponse{} }
func (m *EditProfileResponse) String() string { return proto.CompactTextString(m) }
func (*EditProfileResponse) ProtoMessage()    {}
func (*EditProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{3}
}

func (m *EditProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileResponse.Unmarshal(m, b)
}
func (m *EditProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileResponse.Marshal(b, m, deterministic)
}
func (m *EditProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileResponse.Merge(m, src)
}
func (m *EditProfileResponse) XXX_Size() int {
	return xxx_messageInfo_EditProfileResponse.Size(m)
}
func (m *EditProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileResponse proto.InternalMessageInfo

func (m *EditProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ImageRequest struct {
	ImageData            []byte   `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageRequest) Reset()         { *m = ImageRequest{} }
func (m *ImageRequest) String() string { return proto.CompactTextString(m) }
func (*ImageRequest) ProtoMessage()    {}
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{4}
}

func (m *ImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageRequest.Unmarshal(m, b)
}
func (m *ImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageRequest.Marshal(b, m, deterministic)
}
func (m *ImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageRequest.Merge(m, src)
}
func (m *ImageRequest) XXX_Size() int {
	return xxx_messageInfo_ImageRequest.Size(m)
}
func (m *ImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageRequest proto.InternalMessageInfo

func (m *ImageRequest) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

func (m *ImageRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ImageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageResponse) Reset()         { *m = ImageResponse{} }
func (m *ImageResponse) String() string { return proto.CompactTextString(m) }
func (*ImageResponse) ProtoMessage()    {}
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4f6db3d15f8caf, []int{5}
}

func (m *ImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageResponse.Unmarshal(m, b)
}
func (m *ImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageResponse.Marshal(b, m, deterministic)
}
func (m *ImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageResponse.Merge(m, src)
}
func (m *ImageResponse) XXX_Size() int {
	return xxx_messageInfo_ImageResponse.Size(m)
}
func (m *ImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImageResponse proto.InternalMessageInfo

func (m *ImageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfileDetailsResponse)(nil), "profileDetailsResponse")
	proto.RegisterType((*ProfileDetailsRequest)(nil), "profileDetailsRequest")
	proto.RegisterType((*EditProfileRequest)(nil), "editProfileRequest")
	proto.RegisterType((*EditProfileResponse)(nil), "editProfileResponse")
	proto.RegisterType((*ImageRequest)(nil), "ImageRequest")
	proto.RegisterType((*ImageResponse)(nil), "ImageResponse")
}

func init() {
	proto.RegisterFile("userprofile.proto", fileDescriptor_cb4f6db3d15f8caf)
}

var fileDescriptor_cb4f6db3d15f8caf = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0x38, 0x4d, 0xc6, 0x49, 0x81, 0x6d, 0x09, 0xab, 0x08, 0xa4, 0x28, 0xa7, 0x20,
	0x21, 0x57, 0x82, 0x0b, 0x1c, 0x9b, 0xa4, 0x20, 0x10, 0x94, 0x28, 0xd0, 0x0b, 0x17, 0xb4, 0xad,
	0x87, 0xb2, 0x22, 0xf1, 0x9a, 0xdd, 0xb5, 0xaa, 0xfe, 0x33, 0x7e, 0x0f, 0xbf, 0x83, 0x03, 0xda,
	0x0f, 0x27, 0xb6, 0x13, 0xe8, 0xcd, 0xef, 0x8d, 0x67, 0x67, 0xde, 0x7b, 0x6b, 0xc3, 0x83, 0x5c,
	0xa1, 0xcc, 0xa4, 0xf8, 0xc6, 0x57, 0x18, 0x67, 0x52, 0x68, 0x31, 0xfe, 0xdd, 0x80, 0x81, 0x67,
	0xe6, 0xa8, 0x19, 0x5f, 0xa9, 0x25, 0xaa, 0x4c, 0xa4, 0x0a, 0xc9, 0x31, 0x84, 0x67, 0x6b, 0xc6,
	0x57, 0x34, 0x18, 0x05, 0x93, 0xee, 0xd2, 0x01, 0x32, 0x84, 0xce, 0x85, 0x42, 0x79, 0xce, 0xd6,
	0x48, 0x1b, 0xb6, 0xb0, 0xc1, 0xe4, 0x31, 0x74, 0x5f, 0x73, 0xa9, 0xb4, 0x2d, 0x36, 0x6d, 0x71,
	0x4b, 0x98, 0xce, 0xf7, 0xcc, 0x17, 0x5b, 0xae, 0xb3, 0xc0, 0xa6, 0x73, 0xca, 0xa5, 0xfe, 0x3e,
	0x67, 0x1a, 0x69, 0xe8, 0x3a, 0x37, 0x04, 0x21, 0xd0, 0x9a, 0x71, 0x7d, 0x4b, 0xdb, 0xb6, 0x60,
	0x9f, 0x09, 0x85, 0x83, 0x99, 0xc8, 0x53, 0x2d, 0x6f, 0xe9, 0x81, 0xa5, 0x0b, 0x48, 0x06, 0xd0,
	0x7e, 0x83, 0x69, 0x82, 0x92, 0x76, 0x46, 0xc1, 0x24, 0x5c, 0x7a, 0x44, 0xee, 0x43, 0x73, 0xca,
	0x05, 0xed, 0xda, 0xb7, 0xcd, 0xa3, 0x51, 0xf8, 0x49, 0x9b, 0x89, 0xe0, 0x14, 0x5a, 0x40, 0x46,
	0x10, 0xbd, 0x13, 0x3c, 0xe5, 0xe9, 0xb5, 0xdd, 0x26, 0xb2, 0xb5, 0x32, 0x65, 0x66, 0x7f, 0x40,
	0xa5, 0xd8, 0x35, 0xd2, 0x9e, 0x9b, 0xed, 0xa1, 0x39, 0x91, 0xaf, 0x0d, 0xdf, 0x77, 0x27, 0x5a,
	0x30, 0x7e, 0x05, 0x0f, 0xeb, 0x1e, 0xff, 0xcc, 0x51, 0x69, 0x33, 0xea, 0xf4, 0xea, 0x0a, 0x95,
	0xfa, 0x2c, 0x7e, 0x60, 0xea, 0x8d, 0x2e, 0x53, 0xe3, 0x3f, 0x01, 0x10, 0x4c, 0xb8, 0x5e, 0xb8,
	0xfe, 0xa2, 0x71, 0x02, 0xf7, 0x66, 0xb9, 0x94, 0x98, 0xea, 0x05, 0x53, 0xea, 0x46, 0xc8, 0xc4,
	0x37, 0xd7, 0xe9, 0x6a, 0x26, 0x8d, 0xff, 0x65, 0xd2, 0xac, 0x65, 0x52, 0xb8, 0xde, 0xda, 0xef,
	0x7a, 0x58, 0x75, 0xdd, 0xbb, 0xdb, 0xde, 0xba, 0x3b, 0x82, 0xe8, 0x1c, 0x6f, 0x36, 0xfb, 0xb9,
	0x94, 0xca, 0x54, 0x5d, 0x7e, 0x67, 0x57, 0xfe, 0x09, 0x1c, 0x55, 0xd4, 0xfb, 0xab, 0x59, 0x0a,
	0x20, 0xa8, 0x04, 0x30, 0xfe, 0x08, 0xbd, 0xb7, 0xc6, 0xf3, 0xc2, 0xa8, 0x27, 0x00, 0x36, 0x83,
	0xaf, 0x09, 0xd3, 0xcc, 0xbe, 0xdc, 0x5b, 0x76, 0x2d, 0x33, 0x67, 0x9a, 0xd5, 0x37, 0x68, 0xec,
	0x6e, 0xf0, 0x14, 0xfa, 0xfe, 0xc0, 0xbb, 0x66, 0x3f, 0xff, 0x15, 0x40, 0x64, 0xbe, 0x05, 0xbf,
	0x2d, 0x39, 0x85, 0xc3, 0x45, 0x25, 0x76, 0x32, 0x88, 0xf7, 0xde, 0x83, 0xe1, 0xa3, 0xf8, 0x1f,
	0xdf, 0xe0, 0x4b, 0x88, 0xce, 0xb6, 0xfa, 0xc9, 0x51, 0xbc, 0x7b, 0x17, 0x86, 0xc7, 0xf1, 0x3e,
	0x8b, 0x9e, 0x41, 0x74, 0x91, 0xad, 0x04, 0x4b, 0xec, 0xf6, 0xa4, 0x1f, 0x97, 0x6d, 0x19, 0x1e,
	0xc6, 0x15, 0x51, 0xd3, 0xf0, 0x4b, 0xf3, 0x24, 0xbb, 0xbc, 0x6c, 0xdb, 0x9f, 0xc2, 0x8b, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x98, 0xc0, 0x94, 0x29, 0x04, 0x00, 0x00,
}
