name: CD
on:
  push:
    branches: [ develop ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy TrekDestiny using  ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd /root/git/TrekDestinyBackend 
            docker compose down 
            git pull origin develop
            docker compose up --build -d 
            docker image prune -f